-- SIG-GCM Brasil — Avaliação de Desempenho Funcional

create table if not exists public.avaliacoes_desempenho (
  id bigint generated by default as identity primary key
);

alter table public.avaliacoes_desempenho
  add column if not exists municipio_id bigint not null,
  add column if not exists guarda_id bigint not null,
  add column if not exists guarda_nome text not null,
  add column if not exists matricula text,
  add column if not exists periodo_tipo text not null default 'MENSAL',
  add column if not exists periodo_referencia text not null,
  add column if not exists tipo_avaliacao text not null default 'AVALIACAO_COMANDO',
  add column if not exists criterios jsonb not null default '[]'::jsonb,
  add column if not exists media_final numeric(5,2) not null default 0,
  add column if not exists conceito text not null default 'REGULAR',
  add column if not exists observacoes_gerais text,
  add column if not exists plano_melhoria text,
  add column if not exists status text not null default 'RASCUNHO',
  add column if not exists avaliador_id text,
  add column if not exists avaliador_nome text,
  add column if not exists avaliador_assinatura_em timestamptz,
  add column if not exists guarda_ciencia_em timestamptz,
  add column if not exists guarda_ciencia_nome text,
  add column if not exists criado_em timestamptz not null default now(),
  add column if not exists atualizado_em timestamptz not null default now();

create index if not exists idx_avaliacoes_desempenho_municipio
  on public.avaliacoes_desempenho (municipio_id, criado_em desc);

create index if not exists idx_avaliacoes_desempenho_guarda
  on public.avaliacoes_desempenho (municipio_id, guarda_id, periodo_referencia);

create index if not exists idx_avaliacoes_desempenho_status
  on public.avaliacoes_desempenho (municipio_id, status);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'avaliacoes_desempenho_media_check'
  ) then
    alter table public.avaliacoes_desempenho
      add constraint avaliacoes_desempenho_media_check
      check (media_final >= 0 and media_final <= 10);
  end if;
end $$;

alter table public.avaliacoes_desempenho disable row level security;

grant select, insert, update, delete
  on public.avaliacoes_desempenho
  to authenticated, anon;

grant usage, select on all sequences in schema public
  to authenticated, anon;

notify pgrst, 'reload schema';
