-- SIG-GCM Brasil — Banco de Horas
-- Compatível com instalações onde banco_horas_guardas já existe.

create table if not exists public.banco_horas_guardas (
  id bigint generated by default as identity primary key
);

alter table public.banco_horas_guardas
  add column if not exists municipio_id bigint,
  add column if not exists guarda_id bigint,
  add column if not exists tipo text default 'CREDITO',
  add column if not exists categoria text default 'HORA_EXTRA',
  add column if not exists data date,
  add column if not exists horas numeric(10,2) default 0,
  add column if not exists motivo text,
  add column if not exists observacoes text,
  add column if not exists origem text default 'MANUAL',
  add column if not exists referencia_id bigint,
  add column if not exists criado_por bigint,
  add column if not exists criado_por_nome text,
  add column if not exists criado_em timestamptz default now(),
  add column if not exists atualizado_em timestamptz default now();

update public.banco_horas_guardas
set
  tipo = coalesce(nullif(upper(tipo), ''), 'CREDITO'),
  categoria = coalesce(nullif(upper(categoria), ''), 'HORA_EXTRA'),
  origem = coalesce(nullif(upper(origem), ''), 'MANUAL'),
  horas = coalesce(horas, 0),
  criado_em = coalesce(criado_em, now()),
  atualizado_em = coalesce(atualizado_em, now());

create table if not exists public.banco_horas_solicitacoes (
  id bigint generated by default as identity primary key,
  municipio_id bigint not null,
  guarda_id bigint not null,
  guarda_nome text not null,
  matricula text,
  data_solicitacao date not null default current_date,
  data_compensacao date not null,
  horas numeric(10,2) not null,
  motivo text not null,
  observacoes text,
  status text not null default 'PENDENTE',
  solicitado_por bigint,
  solicitado_por_nome text,
  decidido_por bigint,
  decidido_por_nome text,
  decisao_observacao text,
  decidido_em timestamptz,
  lancamento_id bigint,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

alter table public.banco_horas_solicitacoes
  add column if not exists municipio_id bigint,
  add column if not exists guarda_id bigint,
  add column if not exists guarda_nome text,
  add column if not exists matricula text,
  add column if not exists data_solicitacao date default current_date,
  add column if not exists data_compensacao date,
  add column if not exists horas numeric(10,2),
  add column if not exists motivo text,
  add column if not exists observacoes text,
  add column if not exists status text default 'PENDENTE',
  add column if not exists solicitado_por bigint,
  add column if not exists solicitado_por_nome text,
  add column if not exists decidido_por bigint,
  add column if not exists decidido_por_nome text,
  add column if not exists decisao_observacao text,
  add column if not exists decidido_em timestamptz,
  add column if not exists lancamento_id bigint,
  add column if not exists criado_em timestamptz default now(),
  add column if not exists atualizado_em timestamptz default now();

create table if not exists public.banco_horas_historico (
  id bigint generated by default as identity primary key,
  municipio_id bigint not null,
  guarda_id bigint,
  solicitacao_id bigint,
  usuario_id bigint,
  usuario_nome text,
  acao text not null,
  descricao text,
  detalhes jsonb,
  criado_em timestamptz not null default now()
);

create index if not exists idx_banco_horas_guarda_data
  on public.banco_horas_guardas (municipio_id, guarda_id, data desc);

create index if not exists idx_banco_horas_tipo
  on public.banco_horas_guardas (municipio_id, tipo, categoria);

create index if not exists idx_banco_horas_solicitacoes_status
  on public.banco_horas_solicitacoes (municipio_id, status, data_compensacao);

create index if not exists idx_banco_horas_solicitacoes_guarda
  on public.banco_horas_solicitacoes (municipio_id, guarda_id, criado_em desc);

create index if not exists idx_banco_horas_historico_guarda
  on public.banco_horas_historico (municipio_id, guarda_id, criado_em desc);

create or replace function public.atualizar_timestamp_banco_horas()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

drop trigger if exists trg_banco_horas_guardas_atualizado
on public.banco_horas_guardas;

create trigger trg_banco_horas_guardas_atualizado
before update on public.banco_horas_guardas
for each row
execute function public.atualizar_timestamp_banco_horas();

drop trigger if exists trg_banco_horas_solicitacoes_atualizado
on public.banco_horas_solicitacoes;

create trigger trg_banco_horas_solicitacoes_atualizado
before update on public.banco_horas_solicitacoes
for each row
execute function public.atualizar_timestamp_banco_horas();

alter table public.banco_horas_guardas disable row level security;
alter table public.banco_horas_solicitacoes disable row level security;
alter table public.banco_horas_historico disable row level security;

grant select, insert, update, delete on public.banco_horas_guardas to authenticated, anon;
grant select, insert, update, delete on public.banco_horas_solicitacoes to authenticated, anon;
grant select, insert, update, delete on public.banco_horas_historico to authenticated, anon;
grant usage, select on all sequences in schema public to authenticated, anon;

notify pgrst, 'reload schema';
