-- SIG-GCM Brasil — Competências e Habilidades

create table if not exists public.competencias_catalogo (
  id bigint generated by default as identity primary key
);

alter table public.competencias_catalogo
  add column if not exists municipio_id bigint not null,
  add column if not exists nome text not null,
  add column if not exists categoria text not null default 'TECNICA',
  add column if not exists descricao text,
  add column if not exists evidencias_esperadas text,
  add column if not exists curso_recomendado_id bigint,
  add column if not exists curso_recomendado_nome text,
  add column if not exists ativo boolean not null default true,
  add column if not exists criado_por_id text,
  add column if not exists criado_por_nome text,
  add column if not exists criado_em timestamptz not null default now(),
  add column if not exists atualizado_em timestamptz not null default now();

create table if not exists public.competencias_matriz_guardas (
  id bigint generated by default as identity primary key
);

alter table public.competencias_matriz_guardas
  add column if not exists municipio_id bigint not null,
  add column if not exists guarda_id bigint not null,
  add column if not exists guarda_nome text not null,
  add column if not exists matricula text,
  add column if not exists competencia_id bigint not null,
  add column if not exists competencia_nome text not null,
  add column if not exists nivel_atual integer not null default 1,
  add column if not exists nivel_exigido integer not null default 1,
  add column if not exists autoavaliacao_nivel integer,
  add column if not exists evidencias text,
  add column if not exists observacao_comando text,
  add column if not exists status_validacao text not null default 'PENDENTE',
  add column if not exists validado_por_id text,
  add column if not exists validado_por_nome text,
  add column if not exists validado_em timestamptz,
  add column if not exists criado_em timestamptz not null default now(),
  add column if not exists atualizado_em timestamptz not null default now();

create unique index if not exists uq_competencia_catalogo_nome
  on public.competencias_catalogo (municipio_id, lower(nome));

create unique index if not exists uq_competencia_guarda
  on public.competencias_matriz_guardas
  (municipio_id, guarda_id, competencia_id);

create index if not exists idx_competencias_catalogo_municipio
  on public.competencias_catalogo (municipio_id, ativo, categoria);

create index if not exists idx_competencias_matriz_guarda
  on public.competencias_matriz_guardas
  (municipio_id, guarda_id, status_validacao);

create index if not exists idx_competencias_matriz_competencia
  on public.competencias_matriz_guardas
  (municipio_id, competencia_id);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'competencia_nivel_atual_check'
  ) then
    alter table public.competencias_matriz_guardas
      add constraint competencia_nivel_atual_check
      check (nivel_atual between 1 and 4);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'competencia_nivel_exigido_check'
  ) then
    alter table public.competencias_matriz_guardas
      add constraint competencia_nivel_exigido_check
      check (nivel_exigido between 1 and 4);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'competencia_autoavaliacao_check'
  ) then
    alter table public.competencias_matriz_guardas
      add constraint competencia_autoavaliacao_check
      check (autoavaliacao_nivel is null or autoavaliacao_nivel between 1 and 4);
  end if;
end $$;

alter table public.competencias_catalogo disable row level security;
alter table public.competencias_matriz_guardas disable row level security;

grant select, insert, update, delete
  on public.competencias_catalogo,
     public.competencias_matriz_guardas
  to authenticated, anon;

grant usage, select on all sequences in schema public
  to authenticated, anon;

notify pgrst, 'reload schema';
