-- SIG-GCM Brasil — Cursos, Capacitações e Certificações

create table if not exists public.capacitacoes_cursos (
  id bigint generated by default as identity primary key
);

alter table public.capacitacoes_cursos
  add column if not exists municipio_id bigint not null,
  add column if not exists nome text not null,
  add column if not exists categoria text not null default 'OUTRO',
  add column if not exists modalidade text not null default 'PRESENCIAL',
  add column if not exists carga_horaria integer not null default 1,
  add column if not exists ementa text,
  add column if not exists objetivos text,
  add column if not exists publico_alvo text,
  add column if not exists obrigatorio boolean not null default false,
  add column if not exists validade_meses integer,
  add column if not exists nota_minima numeric(4,2) not null default 7,
  add column if not exists frequencia_minima integer not null default 75,
  add column if not exists status text not null default 'ATIVO',
  add column if not exists criado_por_id text,
  add column if not exists criado_por_nome text,
  add column if not exists criado_em timestamptz not null default now(),
  add column if not exists atualizado_em timestamptz not null default now();

create table if not exists public.capacitacoes_turmas (
  id bigint generated by default as identity primary key
);

alter table public.capacitacoes_turmas
  add column if not exists municipio_id bigint not null,
  add column if not exists curso_id bigint not null,
  add column if not exists curso_nome text not null,
  add column if not exists codigo text not null,
  add column if not exists instrutor_nome text,
  add column if not exists local text,
  add column if not exists modalidade text,
  add column if not exists data_inicio date not null,
  add column if not exists data_fim date not null,
  add column if not exists vagas integer not null default 30,
  add column if not exists status text not null default 'PLANEJADA',
  add column if not exists criado_por_id text,
  add column if not exists criado_por_nome text,
  add column if not exists criado_em timestamptz not null default now(),
  add column if not exists atualizado_em timestamptz not null default now();

create table if not exists public.capacitacoes_matriculas (
  id bigint generated by default as identity primary key
);

alter table public.capacitacoes_matriculas
  add column if not exists municipio_id bigint not null,
  add column if not exists turma_id bigint not null,
  add column if not exists curso_id bigint not null,
  add column if not exists guarda_id bigint not null,
  add column if not exists guarda_nome text not null,
  add column if not exists matricula text,
  add column if not exists frequencia_percentual numeric(5,2) not null default 0,
  add column if not exists nota_final numeric(4,2),
  add column if not exists status text not null default 'INSCRITO',
  add column if not exists certificado_numero text,
  add column if not exists certificado_emitido_em timestamptz,
  add column if not exists validade_certificacao date,
  add column if not exists observacao text,
  add column if not exists inscrito_por_id text,
  add column if not exists inscrito_por_nome text,
  add column if not exists criado_em timestamptz not null default now(),
  add column if not exists atualizado_em timestamptz not null default now();

create unique index if not exists uq_capacitacoes_turma_codigo
  on public.capacitacoes_turmas (municipio_id, codigo);

create unique index if not exists uq_capacitacoes_matricula_guarda_turma
  on public.capacitacoes_matriculas (turma_id, guarda_id);

create index if not exists idx_capacitacoes_cursos_municipio
  on public.capacitacoes_cursos (municipio_id, status, nome);

create index if not exists idx_capacitacoes_turmas_curso
  on public.capacitacoes_turmas (municipio_id, curso_id, data_inicio desc);

create index if not exists idx_capacitacoes_matriculas_guarda
  on public.capacitacoes_matriculas (municipio_id, guarda_id, status);

create index if not exists idx_capacitacoes_certificados_validade
  on public.capacitacoes_matriculas (municipio_id, validade_certificacao)
  where validade_certificacao is not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'capacitacoes_carga_horaria_check'
  ) then
    alter table public.capacitacoes_cursos
      add constraint capacitacoes_carga_horaria_check
      check (carga_horaria > 0);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'capacitacoes_nota_minima_check'
  ) then
    alter table public.capacitacoes_cursos
      add constraint capacitacoes_nota_minima_check
      check (nota_minima >= 0 and nota_minima <= 10);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'capacitacoes_frequencia_minima_check'
  ) then
    alter table public.capacitacoes_cursos
      add constraint capacitacoes_frequencia_minima_check
      check (frequencia_minima >= 0 and frequencia_minima <= 100);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'capacitacoes_matricula_frequencia_check'
  ) then
    alter table public.capacitacoes_matriculas
      add constraint capacitacoes_matricula_frequencia_check
      check (frequencia_percentual >= 0 and frequencia_percentual <= 100);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'capacitacoes_matricula_nota_check'
  ) then
    alter table public.capacitacoes_matriculas
      add constraint capacitacoes_matricula_nota_check
      check (nota_final is null or (nota_final >= 0 and nota_final <= 10));
  end if;
end $$;

alter table public.capacitacoes_cursos disable row level security;
alter table public.capacitacoes_turmas disable row level security;
alter table public.capacitacoes_matriculas disable row level security;

grant select, insert, update, delete
  on public.capacitacoes_cursos,
     public.capacitacoes_turmas,
     public.capacitacoes_matriculas
  to authenticated, anon;

grant usage, select on all sequences in schema public
  to authenticated, anon;

notify pgrst, 'reload schema';
