-- SIG-GCM Brasil — Escala Extraordinária e Eventos

create table if not exists public.escalas_extras (
  id bigint generated by default as identity primary key
);

alter table public.escalas_extras
  add column if not exists municipio_id bigint,
  add column if not exists titulo text,
  add column if not exists descricao text,
  add column if not exists tipo text default 'EVENTO',
  add column if not exists local text,
  add column if not exists endereco text,
  add column if not exists data date,
  add column if not exists hora_inicio time,
  add column if not exists hora_fim time,
  add column if not exists efetivo_necessario integer default 1,
  add column if not exists comandante_id bigint,
  add column if not exists comandante_nome text,
  add column if not exists viatura_id bigint,
  add column if not exists viatura_prefixo text,
  add column if not exists ordem_servico_id bigint,
  add column if not exists status text default 'RASCUNHO',
  add column if not exists observacao text,
  add column if not exists relatorio_final text,
  add column if not exists total_presentes integer default 0,
  add column if not exists total_ausentes integer default 0,
  add column if not exists contabilizar_banco_horas boolean default true,
  add column if not exists criado_por bigint,
  add column if not exists criado_por_nome text,
  add column if not exists criado_em timestamptz default now(),
  add column if not exists atualizado_em timestamptz default now(),
  add column if not exists finalizado_em timestamptz;

create table if not exists public.escalas_extras_convocados (
  id bigint generated by default as identity primary key,
  municipio_id bigint not null,
  escala_extra_id bigint not null,
  guarda_id bigint not null,
  guarda_nome text not null,
  matricula text,
  funcao text default 'PATRULHEIRO',
  status_convocacao text default 'CONVOCADO',
  confirmou_em timestamptz,
  presenca text default 'NAO_REGISTRADA',
  hora_entrada time,
  hora_saida time,
  horas_computadas numeric(10,2) default 0,
  observacao text,
  substituido_por_id bigint,
  substituido_por_nome text,
  banco_horas_lancamento_id bigint,
  criado_em timestamptz default now(),
  atualizado_em timestamptz default now(),
  unique (escala_extra_id, guarda_id)
);

create table if not exists public.escalas_extras_historico (
  id bigint generated by default as identity primary key,
  municipio_id bigint not null,
  escala_extra_id bigint not null,
  usuario_id bigint,
  usuario_nome text,
  acao text not null,
  descricao text,
  detalhes jsonb,
  criado_em timestamptz default now()
);

create index if not exists idx_escalas_extras_municipio_data
  on public.escalas_extras (municipio_id, data desc, status);

create index if not exists idx_escalas_extras_convocados_escala
  on public.escalas_extras_convocados (municipio_id, escala_extra_id, presenca);

create index if not exists idx_escalas_extras_convocados_guarda
  on public.escalas_extras_convocados (municipio_id, guarda_id, criado_em desc);

create index if not exists idx_escalas_extras_historico
  on public.escalas_extras_historico (municipio_id, escala_extra_id, criado_em desc);

create or replace function public.atualizar_timestamp_escalas_extras()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

drop trigger if exists trg_escalas_extras_atualizado on public.escalas_extras;
create trigger trg_escalas_extras_atualizado
before update on public.escalas_extras
for each row execute function public.atualizar_timestamp_escalas_extras();

drop trigger if exists trg_escalas_extras_convocados_atualizado
on public.escalas_extras_convocados;
create trigger trg_escalas_extras_convocados_atualizado
before update on public.escalas_extras_convocados
for each row execute function public.atualizar_timestamp_escalas_extras();

alter table public.escalas_extras disable row level security;
alter table public.escalas_extras_convocados disable row level security;
alter table public.escalas_extras_historico disable row level security;

grant select, insert, update, delete on public.escalas_extras to authenticated, anon;
grant select, insert, update, delete on public.escalas_extras_convocados to authenticated, anon;
grant select, insert, update, delete on public.escalas_extras_historico to authenticated, anon;
grant usage, select on all sequences in schema public to authenticated, anon;

notify pgrst, 'reload schema';
