-- SIG-GCM Brasil — Férias, Licenças e Afastamentos
-- Migração compatível com tabela ferias_licencas já existente.

create table if not exists public.ferias_licencas (
  id bigint generated by default as identity primary key
);

alter table public.ferias_licencas
  add column if not exists municipio_id bigint,
  add column if not exists guarda_id bigint,
  add column if not exists guarda_nome text,
  add column if not exists matricula text,
  add column if not exists tipo text default 'FERIAS',
  add column if not exists modalidade text default 'INTEGRAL',
  add column if not exists data_inicio date,
  add column if not exists data_fim date,
  add column if not exists quantidade_dias integer,
  add column if not exists ano_referencia integer,
  add column if not exists periodo_numero integer default 1,
  add column if not exists motivo text,
  add column if not exists observacao text,
  add column if not exists status text default 'PENDENTE',
  add column if not exists origem text default 'SOLICITACAO',
  add column if not exists bloqueia_escala boolean default true,
  add column if not exists permite_extra_apoio boolean default false,
  add column if not exists solicitado_por bigint,
  add column if not exists solicitado_por_nome text,
  add column if not exists aprovado_por bigint,
  add column if not exists aprovado_por_nome text,
  add column if not exists aprovado_em timestamptz,
  add column if not exists decisao_observacao text,
  add column if not exists cancelado_por bigint,
  add column if not exists cancelado_por_nome text,
  add column if not exists cancelado_em timestamptz,
  add column if not exists cancelamento_motivo text,
  add column if not exists documento_url text,
  add column if not exists documento_nome text,
  add column if not exists criado_em timestamptz default now(),
  add column if not exists atualizado_em timestamptz default now();

update public.ferias_licencas
set
  tipo = coalesce(nullif(upper(replace(tipo, ' ', '_')), ''), 'FERIAS'),
  status = case
    when upper(coalesce(status, '')) in ('ATIVO','APROVADO') then 'APROVADO'
    when upper(coalesce(status, '')) in ('NEGADO','RECUSADO') then 'NEGADO'
    when upper(coalesce(status, '')) = 'CANCELADO' then 'CANCELADO'
    when upper(coalesce(status, '')) = 'FINALIZADO' then 'FINALIZADO'
    else coalesce(nullif(upper(status), ''), 'PENDENTE')
  end,
  quantidade_dias = case
    when data_inicio is not null and data_fim is not null
      then (data_fim - data_inicio) + 1
    else quantidade_dias
  end,
  bloqueia_escala = coalesce(bloqueia_escala, true),
  criado_em = coalesce(criado_em, now()),
  atualizado_em = coalesce(atualizado_em, now());

create table if not exists public.ferias_licencas_historico (
  id bigint generated by default as identity primary key,
  municipio_id bigint not null,
  registro_id bigint not null,
  guarda_id bigint,
  usuario_id bigint,
  usuario_nome text,
  acao text not null,
  descricao text,
  detalhes jsonb,
  criado_em timestamptz not null default now()
);

create index if not exists idx_ferias_licencas_municipio_status
  on public.ferias_licencas (municipio_id, status, data_inicio);

create index if not exists idx_ferias_licencas_guarda
  on public.ferias_licencas (municipio_id, guarda_id, data_inicio desc);

create index if not exists idx_ferias_licencas_periodo
  on public.ferias_licencas (municipio_id, data_inicio, data_fim);

create index if not exists idx_ferias_licencas_historico
  on public.ferias_licencas_historico (municipio_id, registro_id, criado_em desc);

create or replace function public.atualizar_ferias_licencas()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em = now();

  if new.data_inicio is not null and new.data_fim is not null then
    new.quantidade_dias = (new.data_fim - new.data_inicio) + 1;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_atualizar_ferias_licencas
on public.ferias_licencas;

create trigger trg_atualizar_ferias_licencas
before insert or update on public.ferias_licencas
for each row
execute function public.atualizar_ferias_licencas();

alter table public.ferias_licencas disable row level security;
alter table public.ferias_licencas_historico disable row level security;

grant select, insert, update, delete on public.ferias_licencas to authenticated, anon;
grant select, insert, update, delete on public.ferias_licencas_historico to authenticated, anon;
grant usage, select on all sequences in schema public to authenticated, anon;

notify pgrst, 'reload schema';
