-- SIG-GCM Brasil — Folha de Ponto e Frequência Mensal

create table if not exists public.folhas_ponto (
  id bigint generated by default as identity primary key
);

alter table public.folhas_ponto
  add column if not exists municipio_id bigint,
  add column if not exists guarda_id bigint,
  add column if not exists guarda_nome text,
  add column if not exists matricula text,
  add column if not exists mes integer,
  add column if not exists ano integer,
  add column if not exists status text default 'ABERTA',
  add column if not exists dias_trabalhados integer default 0,
  add column if not exists faltas integer default 0,
  add column if not exists atrasos integer default 0,
  add column if not exists minutos_trabalhados integer default 0,
  add column if not exists minutos_extras integer default 0,
  add column if not exists minutos_debito integer default 0,
  add column if not exists afastamentos integer default 0,
  add column if not exists observacao text,
  add column if not exists dados_snapshot jsonb default '[]'::jsonb,
  add column if not exists fechado_por bigint,
  add column if not exists fechado_por_nome text,
  add column if not exists fechado_em timestamptz,
  add column if not exists assinatura_guarda_nome text,
  add column if not exists assinatura_guarda_em timestamptz,
  add column if not exists assinatura_responsavel_nome text,
  add column if not exists assinatura_responsavel_em timestamptz,
  add column if not exists criado_em timestamptz default now(),
  add column if not exists atualizado_em timestamptz default now();

create unique index if not exists uq_folhas_ponto_competencia
  on public.folhas_ponto (municipio_id, guarda_id, ano, mes);

create index if not exists idx_folhas_ponto_municipio_competencia
  on public.folhas_ponto (municipio_id, ano desc, mes desc, status);

create table if not exists public.folhas_ponto_historico (
  id bigint generated by default as identity primary key,
  municipio_id bigint not null,
  folha_ponto_id bigint not null,
  guarda_id bigint,
  usuario_id bigint,
  usuario_nome text,
  acao text not null,
  descricao text,
  detalhes jsonb,
  criado_em timestamptz default now()
);

create index if not exists idx_folhas_ponto_historico
  on public.folhas_ponto_historico
  (municipio_id, folha_ponto_id, criado_em desc);

create or replace function public.atualizar_folha_ponto()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

drop trigger if exists trg_atualizar_folha_ponto on public.folhas_ponto;
create trigger trg_atualizar_folha_ponto
before update on public.folhas_ponto
for each row execute function public.atualizar_folha_ponto();

alter table public.folhas_ponto disable row level security;
alter table public.folhas_ponto_historico disable row level security;

grant select, insert, update, delete on public.folhas_ponto to authenticated, anon;
grant select, insert, update, delete on public.folhas_ponto_historico to authenticated, anon;
grant usage, select on all sequences in schema public to authenticated, anon;

notify pgrst, 'reload schema';
