-- SIG-GCM Brasil - Meu Plantão
create table if not exists public.meu_plantao_registros (
  id bigint generated by default as identity primary key,
  municipio_id bigint not null references public.municipios(id) on delete cascade,
  usuario_id bigint not null,
  guarda_id bigint null references public.guardas(id) on delete set null,
  escala_id bigint null references public.escalas_servico(id) on delete set null,
  data_servico date not null,
  tipo text not null check (tipo in ('CHECK_IN', 'CHECK_OUT')),
  registrado_em timestamptz not null default now(),
  latitude double precision null,
  longitude double precision null,
  observacao text null,
  created_at timestamptz not null default now()
);

create index if not exists idx_meu_plantao_registros_municipio_data
  on public.meu_plantao_registros (municipio_id, data_servico);

create index if not exists idx_meu_plantao_registros_usuario_data
  on public.meu_plantao_registros (usuario_id, data_servico);

create unique index if not exists uq_meu_plantao_checkin_diario
  on public.meu_plantao_registros (municipio_id, usuario_id, data_servico, tipo);

alter table public.meu_plantao_registros enable row level security;

drop policy if exists "meu_plantao_select" on public.meu_plantao_registros;
create policy "meu_plantao_select"
on public.meu_plantao_registros
for select
to authenticated
using (true);

drop policy if exists "meu_plantao_insert" on public.meu_plantao_registros;
create policy "meu_plantao_insert"
on public.meu_plantao_registros
for insert
to authenticated
with check (true);

notify pgrst, 'reload schema';
