-- SIG-GCM Brasil — Plano de Desenvolvimento Individual

create table if not exists public.planos_desenvolvimento_individual (
  id bigint generated by default as identity primary key
);

alter table public.planos_desenvolvimento_individual
  add column if not exists municipio_id bigint not null,
  add column if not exists guarda_id bigint not null,
  add column if not exists guarda_nome text not null,
  add column if not exists matricula text,
  add column if not exists avaliacao_id bigint,
  add column if not exists titulo text not null,
  add column if not exists objetivo_geral text,
  add column if not exists data_inicio date not null default current_date,
  add column if not exists data_fim date,
  add column if not exists metas jsonb not null default '[]'::jsonb,
  add column if not exists progresso integer not null default 0,
  add column if not exists status text not null default 'RASCUNHO',
  add column if not exists observacoes text,
  add column if not exists acompanhamentos jsonb not null default '[]'::jsonb,
  add column if not exists responsavel_id text,
  add column if not exists responsavel_nome text,
  add column if not exists responsavel_assinatura_em timestamptz,
  add column if not exists guarda_ciencia_em timestamptz,
  add column if not exists guarda_ciencia_nome text,
  add column if not exists criado_em timestamptz not null default now(),
  add column if not exists atualizado_em timestamptz not null default now();

create index if not exists idx_pdi_municipio
  on public.planos_desenvolvimento_individual (municipio_id, criado_em desc);

create index if not exists idx_pdi_guarda
  on public.planos_desenvolvimento_individual (municipio_id, guarda_id, status);

create index if not exists idx_pdi_avaliacao
  on public.planos_desenvolvimento_individual (avaliacao_id)
  where avaliacao_id is not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'pdi_progresso_check'
  ) then
    alter table public.planos_desenvolvimento_individual
      add constraint pdi_progresso_check
      check (progresso >= 0 and progresso <= 100);
  end if;
end $$;

alter table public.planos_desenvolvimento_individual disable row level security;

grant select, insert, update, delete
  on public.planos_desenvolvimento_individual
  to authenticated, anon;

grant usage, select on all sequences in schema public
  to authenticated, anon;

notify pgrst, 'reload schema';
