-- SIG-GCM Brasil — Ponto Eletrônico e Controle de Frequência

create table if not exists public.ponto_eletronico (
  id bigint generated by default as identity primary key
);

alter table public.ponto_eletronico
  add column if not exists municipio_id bigint,
  add column if not exists guarda_id bigint,
  add column if not exists guarda_nome text,
  add column if not exists matricula text,
  add column if not exists data date default current_date,
  add column if not exists entrada_em timestamptz,
  add column if not exists saida_em timestamptz,
  add column if not exists entrada_latitude numeric(10,7),
  add column if not exists entrada_longitude numeric(10,7),
  add column if not exists saida_latitude numeric(10,7),
  add column if not exists saida_longitude numeric(10,7),
  add column if not exists entrada_precisao_metros numeric(10,2),
  add column if not exists saida_precisao_metros numeric(10,2),
  add column if not exists entrada_foto text,
  add column if not exists saida_foto text,
  add column if not exists jornada_prevista_inicio time,
  add column if not exists jornada_prevista_fim time,
  add column if not exists minutos_previstos integer default 0,
  add column if not exists minutos_trabalhados integer default 0,
  add column if not exists minutos_atraso integer default 0,
  add column if not exists minutos_extras integer default 0,
  add column if not exists minutos_debito integer default 0,
  add column if not exists tolerancia_minutos integer default 10,
  add column if not exists situacao text default 'ABERTO',
  add column if not exists origem text default 'CELULAR',
  add column if not exists observacao text,
  add column if not exists justificativa text,
  add column if not exists justificativa_status text,
  add column if not exists justificativa_analisada_por bigint,
  add column if not exists justificativa_analisada_por_nome text,
  add column if not exists justificativa_analisada_em timestamptz,
  add column if not exists banco_horas_credito_id bigint,
  add column if not exists banco_horas_debito_id bigint,
  add column if not exists criado_por bigint,
  add column if not exists criado_por_nome text,
  add column if not exists criado_em timestamptz default now(),
  add column if not exists atualizado_em timestamptz default now();

create table if not exists public.ponto_eletronico_configuracao (
  id bigint generated by default as identity primary key,
  municipio_id bigint not null unique,
  tolerancia_atraso_minutos integer default 10,
  exigir_gps boolean default true,
  exigir_foto_entrada boolean default false,
  exigir_foto_saida boolean default false,
  raio_maximo_metros integer default 500,
  latitude_base numeric(10,7),
  longitude_base numeric(10,7),
  lancar_banco_horas boolean default true,
  criado_em timestamptz default now(),
  atualizado_em timestamptz default now()
);

create table if not exists public.ponto_eletronico_historico (
  id bigint generated by default as identity primary key,
  municipio_id bigint not null,
  ponto_id bigint not null,
  guarda_id bigint,
  usuario_id bigint,
  usuario_nome text,
  acao text not null,
  descricao text,
  detalhes jsonb,
  criado_em timestamptz default now()
);

create index if not exists idx_ponto_eletronico_municipio_data
  on public.ponto_eletronico (municipio_id, data desc, situacao);

create index if not exists idx_ponto_eletronico_guarda_data
  on public.ponto_eletronico (municipio_id, guarda_id, data desc);

create index if not exists idx_ponto_eletronico_justificativa
  on public.ponto_eletronico (municipio_id, justificativa_status, data desc);

create index if not exists idx_ponto_eletronico_historico
  on public.ponto_eletronico_historico (municipio_id, ponto_id, criado_em desc);

create or replace function public.atualizar_ponto_eletronico()
returns trigger
language plpgsql
as $$
declare
  minutos_total integer;
  minutos_previstos_calculados integer;
  atraso_calculado integer;
begin
  new.atualizado_em = now();

  if new.entrada_em is not null and new.saida_em is not null then
    minutos_total := greatest(
      0,
      floor(extract(epoch from (new.saida_em - new.entrada_em)) / 60)::integer
    );
    new.minutos_trabalhados := minutos_total;
    new.situacao := case
      when new.situacao = 'CANCELADO' then 'CANCELADO'
      else 'FECHADO'
    end;
  end if;

  if new.jornada_prevista_inicio is not null
     and new.jornada_prevista_fim is not null then
    minutos_previstos_calculados :=
      floor(
        extract(
          epoch from (
            (current_date + new.jornada_prevista_fim) -
            (current_date + new.jornada_prevista_inicio)
          )
        ) / 60
      )::integer;

    if minutos_previstos_calculados <= 0 then
      minutos_previstos_calculados := minutos_previstos_calculados + 1440;
    end if;

    new.minutos_previstos := minutos_previstos_calculados;
  end if;

  if new.entrada_em is not null and new.jornada_prevista_inicio is not null then
    atraso_calculado := greatest(
      0,
      floor(
        extract(
          epoch from (
            new.entrada_em -
            (new.data + new.jornada_prevista_inicio)
          )
        ) / 60
      )::integer - coalesce(new.tolerancia_minutos, 0)
    );
    new.minutos_atraso := atraso_calculado;
  end if;

  if new.minutos_trabalhados > 0 and new.minutos_previstos > 0 then
    new.minutos_extras := greatest(
      0,
      new.minutos_trabalhados - new.minutos_previstos
    );
    new.minutos_debito := greatest(
      0,
      new.minutos_previstos - new.minutos_trabalhados
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_atualizar_ponto_eletronico
on public.ponto_eletronico;

create trigger trg_atualizar_ponto_eletronico
before insert or update on public.ponto_eletronico
for each row
execute function public.atualizar_ponto_eletronico();

drop trigger if exists trg_atualizar_ponto_configuracao
on public.ponto_eletronico_configuracao;

create or replace function public.atualizar_ponto_configuracao()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

create trigger trg_atualizar_ponto_configuracao
before update on public.ponto_eletronico_configuracao
for each row
execute function public.atualizar_ponto_configuracao();

alter table public.ponto_eletronico disable row level security;
alter table public.ponto_eletronico_configuracao disable row level security;
alter table public.ponto_eletronico_historico disable row level security;

grant select, insert, update, delete on public.ponto_eletronico to authenticated, anon;
grant select, insert, update, delete on public.ponto_eletronico_configuracao to authenticated, anon;
grant select, insert, update, delete on public.ponto_eletronico_historico to authenticated, anon;
grant usage, select on all sequences in schema public to authenticated, anon;

notify pgrst, 'reload schema';
