-- SIG-GCM Brasil — Relatório de Frequência e Produtividade
-- Armazena exportações/fechamentos opcionais do relatório gerencial.

create table if not exists public.relatorios_produtividade_historico (
  id bigint generated by default as identity primary key
);

alter table public.relatorios_produtividade_historico
  add column if not exists municipio_id bigint,
  add column if not exists data_inicial date,
  add column if not exists data_final date,
  add column if not exists filtros jsonb default '{}'::jsonb,
  add column if not exists resumo jsonb default '{}'::jsonb,
  add column if not exists dados jsonb default '[]'::jsonb,
  add column if not exists gerado_por bigint,
  add column if not exists gerado_por_nome text,
  add column if not exists criado_em timestamptz default now();

create index if not exists idx_relatorios_produtividade_historico
  on public.relatorios_produtividade_historico
  (municipio_id, data_inicial desc, data_final desc, criado_em desc);

alter table public.relatorios_produtividade_historico disable row level security;

grant select, insert, update, delete
  on public.relatorios_produtividade_historico
  to authenticated, anon;

grant usage, select on all sequences in schema public
  to authenticated, anon;

notify pgrst, 'reload schema';
