-- SIG-GCM Brasil — Sindicâncias e PAD
-- Migração segura: preserva estruturas existentes e adiciona somente o que faltar.

create table if not exists public.processos_disciplinares (
  id bigint generated by default as identity primary key
);

alter table public.processos_disciplinares
  add column if not exists municipio_id bigint,
  add column if not exists numero text,
  add column if not exists tipo text default 'SINDICANCIA',
  add column if not exists titulo text,
  add column if not exists assunto text,
  add column if not exists descricao text,
  add column if not exists origem text,
  add column if not exists natureza text,
  add column if not exists sigilo text default 'RESTRITO',
  add column if not exists prioridade text default 'NORMAL',
  add column if not exists status text default 'INSTAURADO',
  add column if not exists data_instauracao date,
  add column if not exists prazo_final date,
  add column if not exists portaria_numero text,
  add column if not exists autoridade_instauradora text,
  add column if not exists presidente_comissao text,
  add column if not exists membros_comissao text,
  add column if not exists guarda_id bigint,
  add column if not exists servidor_nome text,
  add column if not exists servidor_matricula text,
  add column if not exists conclusao text,
  add column if not exists decisao_final text,
  add column if not exists penalidade text,
  add column if not exists arquivado_em timestamptz,
  add column if not exists concluido_em timestamptz,
  add column if not exists criado_por bigint,
  add column if not exists criado_por_nome text,
  add column if not exists criado_em timestamptz default now(),
  add column if not exists atualizado_em timestamptz default now();

create table if not exists public.processos_disciplinares_movimentacoes (
  id bigint generated by default as identity primary key,
  municipio_id bigint not null,
  processo_id bigint not null references public.processos_disciplinares(id) on delete cascade,
  tipo text not null,
  titulo text not null,
  descricao text,
  data_movimentacao date not null default current_date,
  prazo_relacionado date,
  usuario_id bigint,
  usuario_nome text,
  criado_em timestamptz not null default now()
);

create table if not exists public.processos_disciplinares_envolvidos (
  id bigint generated by default as identity primary key,
  municipio_id bigint not null,
  processo_id bigint not null references public.processos_disciplinares(id) on delete cascade,
  guarda_id bigint,
  nome text not null,
  matricula text,
  papel text not null default 'INVESTIGADO',
  observacoes text,
  criado_em timestamptz not null default now()
);

create table if not exists public.processos_disciplinares_documentos (
  id bigint generated by default as identity primary key,
  municipio_id bigint not null,
  processo_id bigint not null references public.processos_disciplinares(id) on delete cascade,
  nome_arquivo text not null,
  url_arquivo text not null,
  tipo_documento text,
  sigiloso boolean not null default true,
  criado_por bigint,
  criado_em timestamptz not null default now()
);

create index if not exists idx_processos_disciplinares_municipio_status
  on public.processos_disciplinares (municipio_id, status);
create index if not exists idx_processos_disciplinares_prazo
  on public.processos_disciplinares (municipio_id, prazo_final);
create index if not exists idx_processos_disciplinares_guarda
  on public.processos_disciplinares (municipio_id, guarda_id);
create index if not exists idx_processos_movimentacoes_processo
  on public.processos_disciplinares_movimentacoes (processo_id, criado_em desc);

create or replace function public.atualizar_processo_disciplinar_timestamp()
returns trigger language plpgsql as $$
begin new.atualizado_em = now(); return new; end;
$$;

drop trigger if exists trg_processos_disciplinares_atualizado on public.processos_disciplinares;
create trigger trg_processos_disciplinares_atualizado
before update on public.processos_disciplinares
for each row execute function public.atualizar_processo_disciplinar_timestamp();

alter table public.processos_disciplinares disable row level security;
alter table public.processos_disciplinares_movimentacoes disable row level security;
alter table public.processos_disciplinares_envolvidos disable row level security;
alter table public.processos_disciplinares_documentos disable row level security;

grant select,insert,update,delete on public.processos_disciplinares to authenticated, anon;
grant select,insert,update,delete on public.processos_disciplinares_movimentacoes to authenticated, anon;
grant select,insert,update,delete on public.processos_disciplinares_envolvidos to authenticated, anon;
grant select,insert,update,delete on public.processos_disciplinares_documentos to authenticated, anon;
grant usage,select on all sequences in schema public to authenticated, anon;

notify pgrst, 'reload schema';