-- SIG-GCM Brasil — Treinamentos Obrigatórios e Reciclagens

create table if not exists public.treinamentos_obrigatorios_regras (
  id bigint generated by default as identity primary key
);

alter table public.treinamentos_obrigatorios_regras
  add column if not exists municipio_id bigint not null,
  add column if not exists curso_id bigint not null,
  add column if not exists curso_nome text not null,
  add column if not exists cargo text,
  add column if not exists funcao text,
  add column if not exists setor text,
  add column if not exists periodicidade_meses integer not null default 12,
  add column if not exists dias_alerta integer not null default 60,
  add column if not exists observacao text,
  add column if not exists ativo boolean not null default true,
  add column if not exists criado_por_id text,
  add column if not exists criado_por_nome text,
  add column if not exists criado_em timestamptz not null default now(),
  add column if not exists atualizado_em timestamptz not null default now();

create table if not exists public.treinamentos_obrigatorios_situacoes (
  id bigint generated by default as identity primary key
);

alter table public.treinamentos_obrigatorios_situacoes
  add column if not exists municipio_id bigint not null,
  add column if not exists regra_id bigint not null,
  add column if not exists guarda_id bigint not null,
  add column if not exists guarda_nome text not null,
  add column if not exists matricula text,
  add column if not exists ultima_conclusao date,
  add column if not exists validade date,
  add column if not exists dispensado boolean not null default false,
  add column if not exists motivo_dispensa text,
  add column if not exists dispensa_inicio date,
  add column if not exists dispensa_fim date,
  add column if not exists convocado_em timestamptz,
  add column if not exists convocacao_observacao text,
  add column if not exists criado_em timestamptz not null default now(),
  add column if not exists atualizado_em timestamptz not null default now();

create unique index if not exists uq_treinamento_regra
  on public.treinamentos_obrigatorios_regras
  (municipio_id, curso_id, coalesce(cargo, ''), coalesce(funcao, ''), coalesce(setor, ''));

create unique index if not exists uq_treinamento_situacao
  on public.treinamentos_obrigatorios_situacoes
  (municipio_id, regra_id, guarda_id);

create index if not exists idx_treinamento_regras_municipio
  on public.treinamentos_obrigatorios_regras
  (municipio_id, ativo, curso_nome);

create index if not exists idx_treinamento_situacoes_guarda
  on public.treinamentos_obrigatorios_situacoes
  (municipio_id, guarda_id, validade);

create index if not exists idx_treinamento_situacoes_validade
  on public.treinamentos_obrigatorios_situacoes
  (municipio_id, validade)
  where validade is not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'treinamento_periodicidade_check'
  ) then
    alter table public.treinamentos_obrigatorios_regras
      add constraint treinamento_periodicidade_check
      check (periodicidade_meses > 0);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'treinamento_dias_alerta_check'
  ) then
    alter table public.treinamentos_obrigatorios_regras
      add constraint treinamento_dias_alerta_check
      check (dias_alerta > 0);
  end if;
end $$;

alter table public.treinamentos_obrigatorios_regras disable row level security;
alter table public.treinamentos_obrigatorios_situacoes disable row level security;

grant select, insert, update, delete
  on public.treinamentos_obrigatorios_regras,
     public.treinamentos_obrigatorios_situacoes
  to authenticated, anon;

grant usage, select on all sequences in schema public
  to authenticated, anon;

notify pgrst, 'reload schema';
