"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Award, BriefcaseBusiness, Eye, FilePlus2, Loader2, Printer, RefreshCw, Search, ShieldCheck, TrendingUp, Users } from "lucide-react";
import ProtecaoModulo from "@/components/ProtecaoModulo";
import { registrarAuditoria } from "@/lib/auditoria";
import { formatarCarreira, lerUsuarioCarreira, podeGerenciarCarreira } from "@/lib/planoCarreira";
import { supabase } from "@/lib/supabase";

type Processo = { id:number; guarda_id:number; guarda_nome:string; matricula:string|null; cargo_atual:string|null; cargo_pretendido:string; tipo_promocao:string; status:string; pontuacao_total:number; percentual_requisitos:number; criado_em:string };

export default function PlanoCarreiraPage(){
 const [usuario]=useState(()=>lerUsuarioCarreira());
 const [dados,setDados]=useState<Processo[]>([]); const [busca,setBusca]=useState(""); const [carregando,setCarregando]=useState(true); const [erro,setErro]=useState("");
 const pode=usuario?podeGerenciarCarreira(usuario.perfil):false;
 const carregar=useCallback(async()=>{ if(!usuario?.municipio_id){setErro("Sessão inválida.");setCarregando(false);return;} setCarregando(true); const {data,error}=await supabase.from("carreira_processos").select("*").eq("municipio_id",usuario.municipio_id).order("criado_em",{ascending:false}); if(error)setErro(error.message); else setDados((data as Processo[])||[]); setCarregando(false);},[usuario]);
 useEffect(()=>{void carregar()},[carregar]);
 const filtrados=useMemo(()=>{const t=busca.toLowerCase().trim(); return dados.filter(x=>`${x.guarda_nome} ${x.matricula||""} ${x.cargo_atual||""} ${x.cargo_pretendido} ${x.status}`.toLowerCase().includes(t))},[busca,dados]);
 const aptos=dados.filter(x=>["APTO","HOMOLOGADO"].includes(x.status)).length; const analise=dados.filter(x=>x.status==="EM_ANALISE").length; const homologados=dados.filter(x=>x.status==="HOMOLOGADO").length;
 async function imprimir(){await registrarAuditoria({modulo:"RH",acao:"IMPRIMIR",tabela:"carreira_processos",descricao:"Impressão do painel de plano de carreira."}); window.print();}
 return <ProtecaoModulo modulo="guardas"><main className="min-h-screen bg-[#020b1c] px-4 py-5 text-white print:bg-white print:text-black lg:px-7"><div className="mx-auto max-w-[1700px] space-y-5">
  <header className="rounded-3xl border border-cyan-400/15 bg-gradient-to-br from-[#07182f] to-[#020b1c] p-5 print:border-black print:bg-white lg:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.22em] text-cyan-300 print:text-black">Gestão de pessoas</p><h1 className="mt-1 text-2xl font-black lg:text-3xl">Plano de Carreira, Promoções e Progressões</h1><p className="mt-2 text-sm text-slate-400 print:text-black">Critérios, análise de aptidão, comissão, pareceres, homologação e histórico funcional.</p></div><div className="flex flex-wrap gap-3 print:hidden"><button onClick={()=>void carregar()} className="inline-flex items-center gap-2 rounded-xl border border-slate-700 px-4 py-3 text-sm font-black"><RefreshCw className="h-4 w-4"/>Atualizar</button><button onClick={()=>void imprimir()} className="inline-flex items-center gap-2 rounded-xl border border-cyan-400/25 px-4 py-3 text-sm font-black text-cyan-300"><Printer className="h-4 w-4"/>Imprimir/PDF</button><Link href="/sistema/plano-carreira/cargos" className="inline-flex items-center gap-2 rounded-xl border border-cyan-400/25 px-4 py-3 text-sm font-black text-cyan-300"><BriefcaseBusiness className="h-4 w-4"/>Cargos e níveis</Link>{pode&&<Link href="/sistema/plano-carreira/novo" className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-3 text-sm font-black text-slate-950"><FilePlus2 className="h-4 w-4"/>Novo processo</Link>}</div></div></header>
  {erro&&<div className="rounded-2xl border border-rose-400/25 bg-rose-400/10 p-4 text-sm text-rose-200">{erro}</div>}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><M titulo="Processos" valor={dados.length} I={Users}/><M titulo="Em análise" valor={analise} I={TrendingUp}/><M titulo="Aptos" valor={aptos} I={ShieldCheck}/><M titulo="Homologados" valor={homologados} I={Award}/></section>
  <label className="flex items-center gap-3 rounded-xl border border-slate-700 bg-[#061326] px-4 print:hidden"><Search className="h-4 w-4 text-slate-500"/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar guarda, matrícula, cargo ou situação..." className="h-12 w-full bg-transparent outline-none"/></label>
  <section className="overflow-x-auto rounded-2xl border border-slate-800 bg-[#061326] print:border-black print:bg-white">{carregando?<div className="flex min-h-[300px] items-center justify-center"><Loader2 className="h-9 w-9 animate-spin text-cyan-300"/></div>:<table className="w-full min-w-[1100px] text-left text-sm"><thead className="border-b border-slate-700 text-[10px] uppercase text-slate-400 print:text-black"><tr><th className="px-4 py-3">Guarda</th><th className="px-4 py-3">Cargo atual</th><th className="px-4 py-3">Pretendido</th><th className="px-4 py-3">Modalidade</th><th className="px-4 py-3">Requisitos</th><th className="px-4 py-3">Pontuação</th><th className="px-4 py-3">Situação</th><th className="px-4 py-3 print:hidden">Ação</th></tr></thead><tbody>{filtrados.map(x=><tr key={x.id} className="border-b border-slate-800/70"><td className="px-4 py-4"><b>{x.guarda_nome}</b><div className="text-xs text-slate-500">{x.matricula||"Sem matrícula"}</div></td><td className="px-4 py-4">{x.cargo_atual||"Não informado"}</td><td className="px-4 py-4 font-black">{x.cargo_pretendido}</td><td className="px-4 py-4">{formatarCarreira(x.tipo_promocao)}</td><td className="px-4 py-4">{Number(x.percentual_requisitos||0).toFixed(0)}%</td><td className="px-4 py-4">{Number(x.pontuacao_total||0).toFixed(1)}</td><td className="px-4 py-4">{formatarCarreira(x.status)}</td><td className="px-4 py-4 print:hidden"><Link href={`/sistema/plano-carreira/${x.id}`} className="inline-flex items-center gap-2 rounded-lg border border-cyan-400/25 px-3 py-2 font-black text-cyan-300"><Eye className="h-4 w-4"/>Abrir</Link></td></tr>)}{!filtrados.length&&<tr><td colSpan={8} className="px-4 py-16 text-center text-slate-500">Nenhum processo encontrado.</td></tr>}</tbody></table>}</section>
 </div></main></ProtecaoModulo>
}
function M({titulo,valor,I}:{titulo:string;valor:number;I:typeof Award}){return <div className="rounded-2xl border border-slate-800 bg-[#061326] p-5 print:border-black print:bg-white"><I className="h-6 w-6 text-cyan-300 print:text-black"/><p className="mt-4 text-[10px] font-black uppercase tracking-wider text-slate-500 print:text-black">{titulo}</p><p className="mt-1 text-xl font-black">{valor}</p></div>}
