"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import {AlertTriangle,CalendarClock,FilePlus2,FolderLock,Loader2,RefreshCw,Search,ShieldAlert,Scale,CheckCircle2} from "lucide-react";
import {supabase} from "@/lib/supabase";
import {classeStatus,fmtData,lerUsuarioCorregedoria,normalizarCorregedoria,podeGerenciarCorregedoria} from "@/lib/corregedoria";

type Processo={id:number;numero:string;tipo:string;titulo:string;assunto:string|null;sigilo:string;prioridade:string;status:string;data_instauracao:string|null;prazo_final:string|null;servidor_nome:string|null;portaria_numero:string|null;criado_em:string};
const filtros=["TODOS","INSTAURADO","EM_INSTRUCAO","SUSPENSO","CONCLUIDO","ARQUIVADO"];
export default function ProcessosDisciplinaresPage(){
 const [usuario]=useState(()=>lerUsuarioCorregedoria()); const [dados,setDados]=useState<Processo[]>([]); const [loading,setLoading]=useState(true); const [erro,setErro]=useState(""); const [busca,setBusca]=useState(""); const [status,setStatus]=useState("TODOS");
 const carregar=useCallback(async()=>{if(!usuario?.municipio_id){setErro("Sessão não identificada.");setLoading(false);return;}setLoading(true);setErro("");const r=await supabase.from("processos_disciplinares").select("id,numero,tipo,titulo,assunto,sigilo,prioridade,status,data_instauracao,prazo_final,servidor_nome,portaria_numero,criado_em").eq("municipio_id",usuario.municipio_id).order("criado_em",{ascending:false});if(r.error){setErro(r.error.code==="42P01"?"Execute supabase/SINDICANCIAS_PAD.sql.":r.error.message);}else setDados((r.data as Processo[])||[]);setLoading(false);},[usuario]);
 useEffect(()=>{void carregar();},[carregar]);
 const visiveis=useMemo(()=>dados.filter(p=>{const q=normalizarCorregedoria(`${p.numero} ${p.titulo} ${p.assunto||""} ${p.servidor_nome||""}`);return(status==="TODOS"||normalizarCorregedoria(p.status)===status)&&(!busca||q.includes(normalizarCorregedoria(busca)));}),[dados,busca,status]);
 const hoje=new Date(); const vencidos=dados.filter(p=>p.prazo_final&&new Date(`${p.prazo_final}T23:59:59`)<hoje&&!['CONCLUIDO','ARQUIVADO'].includes(normalizarCorregedoria(p.status))).length;
 return <main className="min-h-screen bg-[#020b1c] px-4 py-5 text-white lg:px-7"><div className="mx-auto max-w-[1700px] space-y-5">
  <header className="rounded-3xl border border-cyan-400/15 bg-gradient-to-br from-[#07182f] to-[#020b1c] p-5 lg:p-7"><div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div className="flex gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl border border-cyan-400/25 bg-cyan-400/10 text-cyan-300"><FolderLock className="h-7 w-7"/></div><div><p className="text-[11px] font-black uppercase tracking-[.22em] text-cyan-300">Corregedoria</p><h1 className="mt-1 text-2xl font-black lg:text-3xl">Sindicâncias e PAD</h1><p className="mt-2 text-sm text-slate-400">Controle reservado de apurações, prazos, instrução e decisões.</p></div></div><div className="flex gap-3"><button onClick={()=>void carregar()} className="inline-flex items-center gap-2 rounded-xl border border-slate-700 px-4 py-3 text-sm font-black"><RefreshCw className="h-4 w-4"/>Atualizar</button>{usuario&&podeGerenciarCorregedoria(usuario.perfil)?<Link href="/sistema/corregedoria/processos/novo" className="inline-flex items-center gap-2 rounded-xl bg-cyan-400 px-4 py-3 text-sm font-black text-slate-950"><FilePlus2 className="h-4 w-4"/>Novo processo</Link>:null}</div></div></header>
  {erro?<div className="rounded-2xl border border-rose-400/25 bg-rose-400/10 p-4 text-rose-200">{erro}</div>:null}
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card t="Total" v={dados.length} i={Scale}/><Card t="Em instrução" v={dados.filter(x=>normalizarCorregedoria(x.status)==='EM_INSTRUCAO').length} i={ShieldAlert}/><Card t="Prazos vencidos" v={vencidos} i={CalendarClock}/><Card t="Concluídos" v={dados.filter(x=>['CONCLUIDO','ARQUIVADO'].includes(normalizarCorregedoria(x.status))).length} i={CheckCircle2}/></section>
  <section className="rounded-2xl border border-slate-800 bg-[#061326] p-4"><div className="grid gap-3 lg:grid-cols-[1fr_auto]"><label className="flex items-center gap-3 rounded-xl border border-slate-700 bg-slate-950/50 px-4"><Search className="h-4 w-4 text-slate-500"/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar número, assunto ou servidor..." className="h-12 w-full bg-transparent outline-none"/></label><div className="flex gap-2 overflow-x-auto">{filtros.map(f=><button key={f} onClick={()=>setStatus(f)} className={`whitespace-nowrap rounded-xl border px-3 py-2 text-xs font-black ${status===f?'border-cyan-400/30 bg-cyan-400/10 text-cyan-300':'border-slate-700 text-slate-400'}`}>{f.replaceAll('_',' ')}</button>)}</div></div></section>
  {loading?<div className="flex min-h-[300px] items-center justify-center"><Loader2 className="h-10 w-10 animate-spin text-cyan-300"/></div>:visiveis.length===0?<div className="rounded-3xl border border-dashed border-slate-700 p-12 text-center"><AlertTriangle className="mx-auto h-10 w-10 text-slate-600"/><p className="mt-4 font-black">Nenhum processo encontrado</p></div>:<section className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{visiveis.map(p=><Link key={p.id} href={`/sistema/corregedoria/processos/${p.id}`} className="rounded-2xl border border-slate-800 bg-[#061326] p-5 transition hover:border-cyan-400/30"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-cyan-300">{p.numero}</p><h2 className="mt-2 text-lg font-black">{p.titulo}</h2></div><span className={`rounded-full border px-2.5 py-1 text-[10px] font-black ${classeStatus(p.status)}`}>{p.status.replaceAll('_',' ')}</span></div><p className="mt-3 line-clamp-2 text-sm text-slate-400">{p.assunto||'Sem assunto informado.'}</p><div className="mt-5 grid gap-2 text-xs text-slate-500 sm:grid-cols-2"><span>Tipo: {p.tipo}</span><span>Sigilo: {p.sigilo}</span><span>Instaurado: {fmtData(p.data_instauracao)}</span><span>Prazo: {fmtData(p.prazo_final)}</span><span className="sm:col-span-2">Envolvido: {p.servidor_nome||'Não informado'}</span></div></Link>)}</section>}
 </div></main>;
}
function Card({t,v,i:I}:{t:string;v:number;i:typeof Scale}){return <div className="rounded-2xl border border-slate-800 bg-[#061326] p-5"><I className="h-5 w-5 text-cyan-300"/><p className="mt-4 text-xs font-black uppercase tracking-wider text-slate-500">{t}</p><p className="mt-1 text-2xl font-black">{v}</p></div>}
