export const MARCAS_MODELOS_CELULARES: Record<string, string[]> = {
  Apple: [
    "iPhone 8",
    "iPhone 8 Plus",
    "iPhone X",
    "iPhone XR",
    "iPhone XS",
    "iPhone 11",
    "iPhone 11 Pro",
    "iPhone 12",
    "iPhone 12 Pro",
    "iPhone 13",
    "iPhone 13 Pro",
    "iPhone 14",
    "iPhone 14 Pro",
    "iPhone 15",
    "iPhone 15 Pro",
    "iPhone 16",
    "iPhone 16 Pro",
    "iPhone 17",
    "Outro iPhone",
  ],
  Samsung: [
    "Galaxy A10",
    "Galaxy A20",
    "Galaxy A30",
    "Galaxy A50",
    "Galaxy A70",
    "Galaxy A71",
    "Galaxy A72",
    "Galaxy A73",
    "Galaxy M10",
    "Galaxy M20",
    "Galaxy M30",
    "Galaxy S20",
    "Galaxy S21",
    "Galaxy S22",
    "Galaxy S23",
    "Galaxy S24",
    "Galaxy Z Flip",
    "Galaxy Z Fold",
    "Outro Samsung",
  ],
  Motorola: [
    "Moto G8",
    "Moto G9",
    "Moto G10",
    "Moto G20",
    "Moto G30",
    "Moto G60",
    "Moto G100",
    "Moto E",
    "Moto Edge",
    "Outro Motorola",
  ],
  Xiaomi: [
    "Redmi Note 8",
    "Redmi Note 9",
    "Redmi Note 10",
    "Redmi Note 11",
    "Redmi Note 12",
    "Redmi Note 13",
    "POCO X3",
    "POCO X5",
    "POCO F5",
    "Mi 9",
    "Mi 10",
    "Mi 11",
    "Outro Xiaomi",
  ],
  Realme: ["Realme C11", "Realme C21", "Realme C55", "Realme 8", "Realme 9", "Outro Realme"],
  Asus: ["Zenfone 5", "Zenfone 6", "Zenfone 7", "Zenfone 8", "ROG Phone", "Outro Asus"],
  LG: ["K10", "K11", "K40", "K50", "K61", "Outro LG"],
  Nokia: ["Nokia 2", "Nokia 3", "Nokia 5", "Nokia 6", "Outro Nokia"],
  Huawei: ["P20", "P30", "P40", "Mate 20", "Mate 30", "Outro Huawei"],
  Honor: ["Honor X7", "Honor X8", "Honor X9", "Honor X9c", "Outro Honor"],
  Oppo: ["Oppo A15", "Oppo A16", "Oppo Reno", "Outro Oppo"],
  Vivo: ["Vivo Y20", "Vivo Y30", "Vivo V20", "Outro Vivo"],
  Tecno: ["Spark", "Camon", "Pova", "Outro Tecno"],
  Infinix: ["Hot", "Note", "Zero", "Outro Infinix"],
  Outro: ["Outro modelo"],
};

export const CORES_CELULAR = [
  "Preto",
  "Branco",
  "Prata",
  "Cinza",
  "Azul",
  "Vermelho",
  "Verde",
  "Dourado",
  "Rosa",
  "Roxo",
  "Grafite",
  "Outra",
];

export const SITUACOES_CELULAR = [
  "APREENDIDO",
  "RECUPERADO",
  "ENCONTRADO",
  "ENTREGUE",
  "DEVOLVIDO",
  "DANIFICADO",
  "SEM IDENTIFICAÇÃO",
];