export const MARCAS_MODELOS_CELULARES: Record<string, string[]> = {
Apple: [
    "iPhone 7",
    "iPhone 7 Plus",
    "iPhone 8",
    "iPhone 8 Plus",
    "iPhone X",
    "iPhone XR",
    "iPhone XS",
    "iPhone XS Max",
    "iPhone 11",
    "iPhone 11 Pro",
    "iPhone 11 Pro Max",
    "iPhone 12",
    "iPhone 12 Mini",
    "iPhone 12 Pro",
    "iPhone 12 Pro Max",
    "iPhone 13",
    "iPhone 13 Mini",
    "iPhone 13 Pro",
    "iPhone 13 Pro Max",
    "iPhone 14",
    "iPhone 14 Plus",
    "iPhone 14 Pro",
    "iPhone 14 Pro Max",
    "iPhone 15",
    "iPhone 15 Plus",
    "iPhone 15 Pro",
    "iPhone 15 Pro Max",
    "iPhone 16",
    "iPhone 16 Plus",
    "iPhone 16 Pro",
    "iPhone 16 Pro Max",
    "Outro iPhone",
  ],

  Samsung: [
    "Galaxy A01",
    "Galaxy A02",
    "Galaxy A03",
    "Galaxy A04",
    "Galaxy A05",
    "Galaxy A10",
    "Galaxy A11",
    "Galaxy A12",
    "Galaxy A13",
    "Galaxy A14",
    "Galaxy A15",
    "Galaxy A20",
    "Galaxy A21",
    "Galaxy A22",
    "Galaxy A23",
    "Galaxy A24",
    "Galaxy A30",
    "Galaxy A31",
    "Galaxy A32",
    "Galaxy A33",
    "Galaxy A34",
    "Galaxy A35",
    "Galaxy A50",
    "Galaxy A51",
    "Galaxy A52",
    "Galaxy A53",
    "Galaxy A54",
    "Galaxy A55",
    "Galaxy S20",
    "Galaxy S21",
    "Galaxy S22",
    "Galaxy S23",
    "Galaxy S24",
    "Galaxy Z Flip",
    "Galaxy Z Fold",
    "Outro Samsung",
  ],

  Motorola: [
    "Moto E5",
    "Moto E6",
    "Moto E7",
    "Moto E13",
    "Moto G7",
    "Moto G8",
    "Moto G9",
    "Moto G10",
    "Moto G20",
    "Moto G22",
    "Moto G23",
    "Moto G30",
    "Moto G31",
    "Moto G32",
    "Moto G52",
    "Moto G53",
    "Moto G54",
    "Moto G60",
    "Moto G73",
    "Moto G84",
    "Moto Edge 20",
    "Moto Edge 30",
    "Moto Edge 40",
    "Outro Motorola",
  ],

  Xiaomi: [
    "Redmi 9",
    "Redmi 10",
    "Redmi 12",
    "Redmi Note 8",
    "Redmi Note 9",
    "Redmi Note 10",
    "Redmi Note 11",
    "Redmi Note 12",
    "Redmi Note 13",
    "POCO X3",
    "POCO X5",
    "POCO X6",
    "POCO F5",
    "POCO F6",
    "Mi 9",
    "Mi 10",
    "Mi 11",
    "Mi 12",
    "Outro Xiaomi",
  ],

  Realme: [
    "Realme C11",
    "Realme C21",
    "Realme C30",
    "Realme C55",
    "Realme 8",
    "Realme 9",
    "Realme 10",
    "Outro Realme",
  ],

  Asus: [
    "Zenfone 5",
    "Zenfone 6",
    "Zenfone 7",
    "Zenfone 8",
    "Zenfone 9",
    "ROG Phone",
    "Outro Asus",
  ],

  LG: [
    "K10",
    "K11",
    "K12",
    "K22",
    "K40",
    "K50",
    "K51",
    "K61",
    "Outro LG",
  ],

  Nokia: [
    "Nokia 1",
    "Nokia 2",
    "Nokia 3",
    "Nokia 5",
    "Nokia 6",
    "Nokia G10",
    "Nokia G20",
    "Outro Nokia",
  ],

  Huawei: [
    "P20",
    "P30",
    "P40",
    "Mate 20",
    "Mate 30",
    "Nova 5T",
    "Outro Huawei",
  ],

  Honor: [
    "Honor X7",
    "Honor X8",
    "Honor X9",
    "Honor X9c",
    "Outro Honor",
  ],

  Oppo: [
    "Oppo A15",
    "Oppo A16",
    "Oppo A17",
    "Oppo Reno",
    "Outro Oppo",
  ],

  Vivo: [
    "Vivo Y20",
    "Vivo Y30",
    "Vivo V20",
    "Outro Vivo",
  ],

  Tecno: [
    "Spark",
    "Camon",
    "Pova",
    "Outro Tecno",
  ],

  Infinix: [
    "Hot",
    "Note",
    "Zero",
    "Outro Infinix",
  ],

  Multilaser: [
    "MS50",
    "MS60",
    "G Max",
    "Outro Multilaser",
  ],

  Positivo: [
    "Twist",
    "Twist 2",
    "Twist 4",
    "Outro Positivo",
  ],

  Outro: ["Outro modelo"],
};

export const CORES_CELULAR = [
  "Preto",
  "Branco",
  "Prata",
  "Cinza",
  "Grafite",
  "Azul",
  "Azul Escuro",
  "Azul Claro",
  "Vermelho",
  "Verde",
  "Verde Claro",
  "Amarelo",
  "Laranja",
  "Rosa",
  "Roxo",
  "Lilás",
  "Dourado",
  "Champagne",
  "Marrom",
  "Bege",
  "Transparente",
  "Multicolorido",
  "Outra",
];

export const SITUACOES_CELULAR = [
   "APREENDIDO",
  "RECUPERADO",
  "ENCONTRADO",
  "ENTREGUE",
  "DEVOLVIDO",
  "RESTITUÍDO",
  "RECOLHIDO",
  "ABANDONADO",
  "FURTADO",
  "ROUBADO",
  "DANIFICADO",
  "QUEBRADO",
  "BLOQUEADO",
  "SEM CHIP",
  "SEM BATERIA",
  "SEM IDENTIFICAÇÃO",
];