export const CATEGORIAS_OBJETO = [
   "Celular",
  "Arma de fogo",
  "Arma branca",
  "Munição",
  "Droga",
  "Documento",
  "Dinheiro",
  "Veículo",
  "Bicicleta",
  "Ferramenta",
  "Eletrônico",
  "Joia",
  "Equipamento",
  "Material de construção",
  "Mercadoria",
  "Medicamento",
  "Bebida",
  "Roupa",
  "Bolsa",
  "Mochila",
  "Chave",
  "Placa veicular",
  "Animal",
  "Material recuperado",
  "Material apreendido",
  "Objeto pessoal",
  "Outro",
];

export const TIPOS_DROGA = [
  "Maconha",
  "Cocaína",
  "Crack",
  "Haxixe",
  "Skunk",
  "Lança-perfume",
  "Ecstasy",
  "LSD",
  "Comprimidos",
  "Substância análoga",
  "Pasta base",
  "Semente de maconha",
  "Outro",
];

export const TIPOS_DOCUMENTO = [
"RG",
  "CPF",
  "CNH",
  "Título de Eleitor",
  "Carteira de Trabalho",
  "Carteira Funcional",
  "Passaporte",
  "CRLV",
  "CRV",
  "Cartão do SUS",
  "Cartão bancário",
  "Certidão de Nascimento",
  "Certidão de Casamento",
  "Comprovante de residência",
  "Outro",
];

export const TIPOS_FERRAMENTA = [
  "Chave de fenda",
  "Alicate",
  "Martelo",
  "Serra",
  "Furadeira",
  "Chave inglesa",
  "Pé de cabra",
  "Marreta",
  "Machado",
  "Enxada",
  "Facão",
  "Tesoura",
  "Estilete",
  "Lixadeira",
  "Parafusadeira",
  "Outro"
];

export const TIPOS_ELETRONICO = [
   "Notebook",
  "Computador",
  "Monitor",
  "Tablet",
  "Televisão",
  "Caixa de som",
  "Relógio",
  "Smartwatch",
  "Câmera",
  "Drone",
  "Videogame",
  "Videogame portátil",
  "Impressora",
  "Roteador",
  "Modem",
  "GPS",
  "Pen drive",
  "HD Externo",
  "Outro",
];

export const SITUACOES_OBJETO_GERAL = [
  "APREENDIDO",
  "RECUPERADO",
  "ENCONTRADO",
  "ENTREGUE",
  "DEVOLVIDO",
  "RESTITUÍDO",
  "RECOLHIDO",
  "ABANDONADO",
  "FURTADO",
  "ROUBADO",
  "EXTRAVIADO",
  "DANIFICADO",
  "DESTRUÍDO",
  "QUEBRADO",
  "LACRADO",
  "PERICIADO",
  "ENCAMINHADO",
  "SEM IDENTIFICAÇÃO",
];