"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Boxes, FilePlus2, HardHat, Loader2, PackageCheck, Printer, RefreshCw, Search, ShieldCheck, TriangleAlert } from "lucide-react";
import ProtecaoModulo from "@/components/ProtecaoModulo";
import { registrarAuditoria } from "@/lib/auditoria";
import { diasAteEpiEpc, formatarDataEpiEpc, formatarEpiEpc, lerUsuarioEpiEpc, podeGerenciarEpiEpc } from "@/lib/epiEpc";
import { supabase } from "@/lib/supabase";

type Item = { id:number; tipo:string; nome:string; ca_numero:string|null; fabricante:string|null; lote:string|null; validade_ca:string|null; validade_lote:string|null; quantidade_estoque:number; estoque_minimo:number; status:string; tamanho:string|null };

export default function EpiEpcPage(){
  const [usuario]=useState(()=>lerUsuarioEpiEpc());
  const [itens,setItens]=useState<Item[]>([]); const [busca,setBusca]=useState(""); const [carregando,setCarregando]=useState(true); const [erro,setErro]=useState("");
  const podeGerenciar=usuario ? podeGerenciarEpiEpc(usuario.perfil) : false;
  const carregar=useCallback(async()=>{ if(!usuario?.municipio_id){setErro("Sessão ou município não identificado.");setCarregando(false);return;} setCarregando(true); setErro(""); const {data,error}=await supabase.from("epi_epc_itens").select("id,tipo,nome,ca_numero,fabricante,lote,validade_ca,validade_lote,quantidade_estoque,estoque_minimo,status,tamanho").eq("municipio_id",usuario.municipio_id).order("nome"); if(error)setErro(error.message); setItens((data as Item[]|null)||[]); setCarregando(false); },[usuario]);
  useEffect(()=>{void carregar();},[carregar]);
  const filtrados=useMemo(()=>{const t=busca.trim().toLowerCase(); return itens.filter(i=>`${i.tipo} ${i.nome} ${i.ca_numero||""} ${i.fabricante||""} ${i.lote||""} ${i.status}`.toLowerCase().includes(t));},[busca,itens]);
  const estoqueBaixo=itens.filter(i=>i.quantidade_estoque<=i.estoque_minimo).length;
  const vencidos=itens.filter(i=>{const d=diasAteEpiEpc(i.validade_ca||i.validade_lote); return d!==null&&d<0;}).length;
  const proximos=itens.filter(i=>{const d=diasAteEpiEpc(i.validade_ca||i.validade_lote); return d!==null&&d>=0&&d<=30;}).length;
  async function imprimir(){await registrarAuditoria({modulo:"PATRIMONIO",acao:"IMPRIMIR",tabela:"epi_epc_itens",descricao:"Impressão do painel de EPI e EPC."}); window.print();}
  return <ProtecaoModulo modulo="patrimonio"><main className="min-h-screen bg-[#020b1c] px-4 py-5 text-white print:bg-white print:text-black lg:px-7"><div className="mx-auto max-w-[1700px] space-y-5">
    <header className="rounded-3xl border border-cyan-400/15 bg-gradient-to-br from-[#07182f] to-[#020b1c] p-5 print:border-black print:bg-white lg:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-cyan-300 print:text-black">Proteção individual e coletiva</p><h1 className="mt-1 text-2xl font-black lg:text-3xl">Controle de EPI e EPC</h1><p className="mt-2 text-sm text-slate-400 print:text-black">Catálogo, estoque, CA, validade, entregas, devoluções e termos de responsabilidade.</p></div><div className="flex flex-wrap gap-3 print:hidden">
      <button onClick={()=>void carregar()} className="inline-flex items-center gap-2 rounded-xl border border-slate-700 px-4 py-3 text-sm font-black"><RefreshCw className="h-4 w-4"/>Atualizar</button>
      <button onClick={()=>void imprimir()} className="inline-flex items-center gap-2 rounded-xl border border-cyan-400/25 bg-cyan-400/10 px-4 py-3 text-sm font-black text-cyan-300"><Printer className="h-4 w-4"/>Imprimir/PDF</button>
      <Link href="/sistema/epi-epc/entregas" className="inline-flex items-center gap-2 rounded-xl border border-cyan-400/25 px-4 py-3 text-sm font-black text-cyan-300"><PackageCheck className="h-4 w-4"/>Entregas</Link>
      {podeGerenciar?<Link href="/sistema/epi-epc/novo" className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-3 text-sm font-black text-slate-950"><FilePlus2 className="h-4 w-4"/>Novo item</Link>:null}
    </div></div></header>
    {erro?<div className="rounded-2xl border border-rose-400/25 bg-rose-400/10 p-4 text-rose-200">{erro}</div>:null}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metrica titulo="Itens" valor={itens.length} icone={Boxes}/><Metrica titulo="EPIs" valor={itens.filter(i=>i.tipo==="EPI").length} icone={HardHat}/><Metrica titulo="EPCs" valor={itens.filter(i=>i.tipo==="EPC").length} icone={ShieldCheck}/><Metrica titulo="Estoque baixo" valor={estoqueBaixo} icone={TriangleAlert}/><Metrica titulo="Vencidos / 30 dias" valor={vencidos+proximos} icone={TriangleAlert}/></section>
    <label className="flex items-center gap-3 rounded-xl border border-slate-700 bg-[#061326] px-4 print:hidden"><Search className="h-4 w-4 text-slate-500"/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar item, CA, fabricante, lote ou status..." className="h-12 w-full bg-transparent outline-none"/></label>
    {carregando?<div className="flex min-h-[300px] items-center justify-center"><Loader2 className="h-9 w-9 animate-spin text-cyan-300"/></div>:<section className="grid gap-4 xl:grid-cols-2">{filtrados.map(item=>{const validade=item.validade_ca||item.validade_lote; const dias=diasAteEpiEpc(validade); return <article key={item.id} className="rounded-2xl border border-slate-800 bg-[#061326] p-5 print:border-black print:bg-white"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-cyan-300 print:text-black">{item.tipo}</p><h2 className="mt-1 text-lg font-black">{item.nome}</h2><p className="mt-1 text-sm text-slate-500 print:text-black">{item.fabricante||"Fabricante não informado"}</p></div><span className="rounded-lg border border-cyan-400/20 bg-cyan-400/10 px-3 py-2 text-[10px] font-black uppercase text-cyan-300 print:text-black">{formatarEpiEpc(item.status)}</span></div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4"><Info titulo="CA" valor={item.ca_numero||"—"}/><Info titulo="Lote" valor={item.lote||"—"}/><Info titulo="Estoque" valor={String(item.quantidade_estoque)}/><Info titulo="Mínimo" valor={String(item.estoque_minimo)}/></div><div className="mt-4 rounded-xl border border-slate-800 bg-slate-950/30 p-4 print:border-black print:bg-white"><p className="text-[10px] font-black uppercase text-slate-500 print:text-black">Validade</p><p className="mt-1 font-black">{formatarDataEpiEpc(validade)} {dias!==null?`• ${dias} dia(s)`:""}</p></div><Link href={`/sistema/epi-epc/${item.id}`} className="mt-4 inline-flex rounded-xl bg-cyan-300 px-4 py-3 text-sm font-black text-slate-950 print:hidden">Abrir item</Link></article>})}{!filtrados.length?<div className="rounded-2xl border border-slate-800 bg-[#061326] p-14 text-center text-slate-500 xl:col-span-2">Nenhum EPI ou EPC cadastrado.</div>:null}</section>}
  </div></main></ProtecaoModulo>
}
function Metrica({titulo,valor,icone:Icone}:{titulo:string;valor:number;icone:typeof Boxes}){return <div className="rounded-2xl border border-slate-800 bg-[#061326] p-5 print:border-black print:bg-white"><Icone className="h-6 w-6 text-cyan-300 print:text-black"/><p className="mt-4 text-[10px] font-black uppercase text-slate-500 print:text-black">{titulo}</p><p className="mt-1 text-xl font-black">{valor}</p></div>}
function Info({titulo,valor}:{titulo:string;valor:string}){return <div className="rounded-xl border border-slate-800 bg-slate-950/30 p-3 text-center print:border-black print:bg-white"><p className="text-[10px] font-black uppercase text-slate-500 print:text-black">{titulo}</p><p className="mt-1 font-black">{valor}</p></div>}
