"use client";
import Link from "next/link"; import { use,useCallback,useEffect,useMemo,useState } from "react"; import { ArrowLeft,CheckCircle2,FileText,Loader2,Printer,Save,ShieldCheck } from "lucide-react";
import ProtecaoModulo from "@/components/ProtecaoModulo"; import { registrarAuditoria } from "@/lib/auditoria"; import { formatarCarreira,lerUsuarioCarreira,podeGerenciarCarreira } from "@/lib/planoCarreira"; import { supabase } from "@/lib/supabase";
type P={id:number;guarda_id:number;guarda_nome:string;matricula:string|null;cargo_atual:string|null;cargo_pretendido:string;tipo_promocao:string;status:string;pontuacao_total:number;percentual_requisitos:number;parecer_comissao:string|null;portaria_numero:string|null;data_homologacao:string|null;observacoes:string|null};
type R={id:number;criterio:string;tipo:string;exigido_texto:string|null;exigido_numero:number|null;resultado_texto:string|null;resultado_numero:number|null;atendido:boolean;pontos:number;observacao:string|null};
export default function Detalhe({params}:{params:Promise<{id:string}>}){const {id}=use(params); const [u]=useState(()=>lerUsuarioCarreira()); const [p,setP]=useState<P|null>(null); const [req,setReq]=useState<R[]>([]); const [erro,setErro]=useState(""); const [loading,setLoading]=useState(true); const pode=u?podeGerenciarCarreira(u.perfil):false;
 const carregar=useCallback(async()=>{if(!u?.municipio_id)return; const [a,b]=await Promise.all([supabase.from("carreira_processos").select("*").eq("id",Number(id)).eq("municipio_id",u.municipio_id).single(),supabase.from("carreira_requisitos_avaliacao").select("*").eq("processo_id",Number(id)).eq("municipio_id",u.municipio_id).order("id")]); if(a.error)setErro(a.error.message);else setP(a.data as P); if(!b.error)setReq((b.data as R[])||[]); setLoading(false)},[id,u]); useEffect(()=>{void carregar()},[carregar]);
 const percentual=useMemo(()=>req.length?req.filter(x=>x.atendido).length/req.length*100:Number(p?.percentual_requisitos||0),[req,p]); const pontos=req.reduce((s,x)=>s+Number(x.pontos||0),0);
 function localReq(rid:number,campo:keyof R,valor:any){setReq(a=>a.map(x=>x.id===rid?{...x,[campo]:valor}:x))}
 async function salvar(homologar=false){if(!u||!p||!pode)return; for(const x of req){const {error}=await supabase.from("carreira_requisitos_avaliacao").update({resultado_texto:x.resultado_texto,resultado_numero:x.resultado_numero,atendido:x.atendido,pontos:x.pontos,observacao:x.observacao}).eq("id",x.id).eq("municipio_id",u.municipio_id); if(error){setErro(error.message);return}} const status=homologar?"HOMOLOGADO":p.status; const {error}=await supabase.from("carreira_processos").update({status,pontuacao_total:pontos,percentual_requisitos:percentual,parecer_comissao:p.parecer_comissao,portaria_numero:p.portaria_numero,data_homologacao:homologar?new Date().toISOString().slice(0,10):p.data_homologacao,atualizado_em:new Date().toISOString()}).eq("id",p.id).eq("municipio_id",u.municipio_id); if(error){setErro(error.message);return} await registrarAuditoria({modulo:"RH",acao:homologar?"HOMOLOGAR":"ATUALIZAR",tabela:"carreira_processos",registro_id:p.id,descricao:`Processo de carreira de ${p.guarda_nome} atualizado.`}); await carregar()}
 async function adicionarPadrao(){if(!u||!p||!pode)return; const base=[['Tempo mínimo no cargo','TEMPO',24],['Cursos obrigatórios','CURSO',1],['Avaliação de desempenho','AVALIACAO',70],['Competências exigidas','COMPETENCIA',1],['Ausência de impedimentos disciplinares','DISCIPLINA',1]]; const rows=base.map(([c,t,n])=>({municipio_id:u.municipio_id,processo_id:p.id,criterio:c,tipo:t,exigido_numero:n,atendido:false,pontos:0})); const {error}=await supabase.from("carreira_requisitos_avaliacao").insert(rows); if(error)setErro(error.message); else await carregar()}
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#020b1c]"><Loader2 className="h-10 w-10 animate-spin text-cyan-300"/></div>; if(!p)return <div className="min-h-screen bg-[#020b1c] p-8 text-white">{erro||"Processo não encontrado."}</div>;
 return <ProtecaoModulo modulo="guardas"><main className="min-h-screen bg-[#020b1c] p-5 text-white print:bg-white print:text-black"><div className="mx-auto max-w-5xl space-y-5"><header className="rounded-3xl border border-cyan-400/15 bg-[#061326] p-6 print:border-black print:bg-white"><div className="flex justify-between gap-4"><div><Link href="/sistema/plano-carreira" className="inline-flex items-center gap-2 text-sm font-black text-cyan-300 print:hidden"><ArrowLeft className="h-4 w-4"/>Voltar</Link><h1 className="mt-4 text-2xl font-black">{p.guarda_nome}</h1><p className="mt-1 text-sm text-slate-400 print:text-black">{p.cargo_atual||"Sem cargo"} → {p.cargo_pretendido}</p></div><button onClick={()=>window.print()} className="self-start rounded-xl border border-cyan-400/25 p-3 text-cyan-300 print:hidden"><Printer className="h-5 w-5"/></button></div></header>{erro&&<div className="rounded-xl border border-rose-400/25 bg-rose-400/10 p-4 text-rose-200">{erro}</div>}<section className="grid gap-3 sm:grid-cols-3"><Box t="Situação" v={formatarCarreira(p.status)}/><Box t="Requisitos atendidos" v={`${percentual.toFixed(0)}%`}/><Box t="Pontuação" v={pontos.toFixed(1)}/></section>
 {pode&&!req.length&&<button onClick={()=>void adicionarPadrao()} className="rounded-xl bg-cyan-300 px-4 py-3 font-black text-slate-950 print:hidden">Gerar requisitos padrão</button>}
 <section className="space-y-3">{req.map(x=><div key={x.id} className="rounded-2xl border border-slate-800 bg-[#061326] p-5 print:border-black print:bg-white"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><b>{x.criterio}</b><p className="text-xs text-slate-500 print:text-black">Exigido: {x.exigido_texto||x.exigido_numero||"-"}</p></div><label className="flex items-center gap-2"><input type="checkbox" checked={x.atendido} onChange={e=>localReq(x.id,'atendido',e.target.checked)}/>Atendido</label></div><div className="mt-4 grid gap-3 md:grid-cols-3"><input value={x.resultado_texto||""} onChange={e=>localReq(x.id,'resultado_texto',e.target.value)} placeholder="Resultado" className="h-11 rounded-xl border border-slate-700 bg-slate-950/60 px-4 print:bg-white"/><input type="number" value={x.pontos} onChange={e=>localReq(x.id,'pontos',Number(e.target.value))} placeholder="Pontos" className="h-11 rounded-xl border border-slate-700 bg-slate-950/60 px-4 print:bg-white"/><input value={x.observacao||""} onChange={e=>localReq(x.id,'observacao',e.target.value)} placeholder="Observação" className="h-11 rounded-xl border border-slate-700 bg-slate-950/60 px-4 print:bg-white"/></div></div>)}</section>
 <section className="grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="text-xs font-black uppercase text-slate-400">Parecer da comissão</span><textarea value={p.parecer_comissao||""} onChange={e=>setP({...p,parecer_comissao:e.target.value})} rows={5} className="w-full rounded-xl border border-slate-700 bg-[#061326] p-4 print:bg-white"/></label><label className="space-y-2"><span className="text-xs font-black uppercase text-slate-400">Número da portaria</span><input value={p.portaria_numero||""} onChange={e=>setP({...p,portaria_numero:e.target.value})} className="h-12 w-full rounded-xl border border-slate-700 bg-[#061326] px-4 print:bg-white"/></label></section>
 {pode&&<div className="flex flex-wrap justify-end gap-3 print:hidden"><button onClick={()=>void salvar(false)} className="inline-flex items-center gap-2 rounded-xl border border-cyan-400/25 px-4 py-3 font-black text-cyan-300"><Save className="h-4 w-4"/>Salvar análise</button><button onClick={()=>void salvar(true)} className="inline-flex items-center gap-2 rounded-xl bg-emerald-400 px-4 py-3 font-black text-slate-950"><ShieldCheck className="h-4 w-4"/>Homologar</button></div>}</div></main></ProtecaoModulo>}
function Box({t,v}:{t:string;v:string}){return <div className="rounded-2xl border border-slate-800 bg-[#061326] p-5 print:border-black print:bg-white"><p className="text-[10px] font-black uppercase text-slate-500 print:text-black">{t}</p><p className="mt-2 text-xl font-black">{v}</p></div>}
