"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Bell, CheckCheck, Clock3, Eye, Filter, Loader2, Search, Trash2 } from "lucide-react";
import ProtecaoModulo from "@/components/ProtecaoModulo";
import SigPageHeader from "@/components/sig/SigPageHeader";
import { supabase } from "@/lib/supabase";

type User={id:string|number;perfil?:string;municipio_id?:number}; type N=Record<string,unknown>;
function user():User|null{try{return JSON.parse(localStorage.getItem("usuarioLogado")||"null") as User|null}catch{return null}}
function tipoClass(t:string){if(t.includes("ALERTA")||t.includes("URGENTE"))return"border-rose-400/25 bg-rose-400/10 text-rose-300";if(t.includes("SUCESSO"))return"border-emerald-400/25 bg-emerald-400/10 text-emerald-300";return"border-cyan-400/25 bg-cyan-400/10 text-cyan-300"}
export default function NotificacoesPage(){const[usuario,setUsuario]=useState<User|null>(null);const[itens,setItens]=useState<N[]>([]);const[busca,setBusca]=useState("");const[filtro,setFiltro]=useState("TODAS");const[loading,setLoading]=useState(true);
const carregar=useCallback(async(u:User)=>{if(!u.municipio_id)return;const{data}=await supabase.from("notificacoes").select("*").eq("municipio_id",u.municipio_id).or(`usuario_id.eq.${u.id},usuario_id.is.null,perfil_destino.eq.${u.perfil||""}`).order("created_at",{ascending:false}).limit(500);setItens((data??[])as N[]);setLoading(false)},[]);
useEffect(()=>{const u=user();setUsuario(u);if(u)void carregar(u);else setLoading(false)},[carregar]);
useEffect(()=>{if(!usuario?.municipio_id)return;const c=supabase.channel(`notif-${usuario.id}`).on("postgres_changes",{event:"*",schema:"public",table:"notificacoes",filter:`municipio_id=eq.${usuario.municipio_id}`},()=>void carregar(usuario)).subscribe();return()=>{void supabase.removeChannel(c)}},[carregar,usuario]);
const filtrados=useMemo(()=>itens.filter(n=>{const l=n.lida===true;const q=`${n.titulo??""} ${n.mensagem??""}`.toLowerCase().includes(busca.toLowerCase());return q&&(filtro==="TODAS"||(filtro==="NAO_LIDAS"&&!l)||(filtro==="LIDAS"&&l))}),[busca,filtro,itens]);
async function marcar(id:unknown,lida=true){await supabase.from("notificacoes").update({lida,lida_em:lida?new Date().toISOString():null}).eq("id",id);if(usuario)await carregar(usuario)}
async function todas(){if(!usuario)return;await supabase.from("notificacoes").update({lida:true,lida_em:new Date().toISOString()}).eq("municipio_id",usuario.municipio_id).or(`usuario_id.eq.${usuario.id},usuario_id.is.null,perfil_destino.eq.${usuario.perfil||""}`);await carregar(usuario)}
return <ProtecaoModulo modulo="notificacoes"><main className="min-h-screen bg-[#020817] p-4 pb-24 text-white md:p-6"><div className="mx-auto max-w-[1500px] space-y-5"><SigPageHeader titulo="Notificações" subtitulo="Alertas e eventos do sistema em tempo real." icone={Bell}/><section className="flex flex-col gap-3 rounded-3xl border border-white/10 bg-[#071225] p-4 md:flex-row"><label className="relative flex-1"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500"/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Pesquisar notificações..." className="h-12 w-full rounded-2xl border border-white/10 bg-[#020817] pl-11 pr-4 outline-none"/></label><select value={filtro} onChange={e=>setFiltro(e.target.value)} className="h-12 rounded-2xl border border-white/10 bg-[#020817] px-4"><option value="TODAS">Todas</option><option value="NAO_LIDAS">Não lidas</option><option value="LIDAS">Lidas</option></select><button onClick={()=>void todas()} className="inline-flex h-12 items-center justify-center gap-2 rounded-2xl bg-cyan-400 px-4 font-black text-slate-950"><CheckCheck className="h-5 w-5"/>Marcar todas</button></section><section className="overflow-hidden rounded-3xl border border-white/10 bg-[#071225]">{loading?<div className="p-20"><Loader2 className="mx-auto h-7 w-7 animate-spin text-cyan-300"/></div>:filtrados.length===0?<div className="p-20 text-center text-slate-500">Nenhuma notificação encontrada.</div>:<div className="divide-y divide-white/[.07]">{filtrados.map(n=>{const l=n.lida===true;const tipo=String(n.tipo??"INFO").toUpperCase();return <div key={String(n.id)} className={`flex items-start gap-4 p-4 md:p-5 ${l?"opacity-60":"bg-cyan-400/[.025]"}`}><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border ${tipoClass(tipo)}`}><Bell className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-black">{String(n.titulo??"Notificação")}</p><p className="mt-2 text-sm leading-6 text-slate-400">{String(n.mensagem??"")}</p></div><span className={`rounded-full border px-2 py-1 text-[9px] font-black ${tipoClass(tipo)}`}>{tipo}</span></div><div className="mt-3 flex flex-wrap items-center gap-3 text-[10px] text-slate-600"><span className="inline-flex items-center gap-1"><Clock3 className="h-3.5 w-3.5"/>{new Date(String(n.created_at??n.criado_em??Date.now())).toLocaleString("pt-BR")}</span>{!l?<button onClick={()=>void marcar(n.id)} className="font-black text-cyan-300">Marcar como lida</button>:<button onClick={()=>void marcar(n.id,false)} className="font-black text-slate-400">Marcar não lida</button>}{n.link?<Link href={String(n.link)} className="inline-flex items-center gap-1 font-black text-cyan-300"><Eye className="h-3.5 w-3.5"/>Abrir</Link>:null}</div></div></div>})}</div>}</section></div></main></ProtecaoModulo>}
