export const TIPOS_OCORRENCIA = [
  "Perturbação do sossego",
  "Averiguação de denúncia",
  "Averiguação de atitude suspeita",
  "Abordagem a pessoa suspeita",
  "Abordagem a veículo suspeito",
  "Pessoa em atitude suspeita",
  "Veículo abandonado",
  "Veículo recuperado",
  "Veículo irregular",
  "Acidente de trânsito",
  "Acidente com vítima",
  "Acidente sem vítima",
  "Atropelamento",
  "Obstrução de via",
  "Apoio ao SAMU",
  "Apoio ao Corpo de Bombeiros",
  "Apoio ao Conselho Tutelar",
  "Apoio à Polícia Militar",
  "Apoio à Polícia Civil",
  "Apoio ao cidadão",
  "Apoio à saúde",
  "Apoio ao CAPS",
  "Apoio ao CRAS",
  "Apoio ao CREAS",
  "Apoio em evento",
  "Apoio em evento esportivo",
  "Apoio em evento cultural",
  "Apoio em evento religioso",
  "Apoio em evento político",
  "Apoio escolar",
  "Ronda escolar",
  "Patrulhamento preventivo",
  "Patrulhamento comercial",
  "Patrulhamento rural",
  "Patrulhamento em prédios públicos",
  "Fiscalização",
  "Fiscalização de trânsito",
  "Fiscalização ambiental",
  "Fiscalização de comércio",
  "Fiscalização de ambulantes",
  "Fiscalização de feira livre",
  "Furto",
  "Roubo",
  "Tentativa de furto",
  "Tentativa de roubo",
  "Dano ao patrimônio",
  "Depredação",
  "Vandalismo",
  "Invasão de patrimônio público",
  "Violência doméstica",
  "Maria da Penha",
  "Ameaça",
  "Vias de fato",
  "Briga",
  "Lesão corporal",
  "Desinteligência familiar",
  "Desordem",
  "Tráfico / Drogas",
  "Uso de entorpecentes",
  "Porte de entorpecentes",
  "Embriaguez",
  "Pessoa desaparecida",
  "Pessoa perdida",
  "Pessoa em situação de rua",
  "Menor em situação de risco",
  "Abandono de incapaz",
  "Maus-tratos",
  "Maus-tratos a animais",
  "Animais soltos",
  "Resgate de animal",
  "Crime ambiental",
  "Poluição sonora",
  "Queimada",
  "Objeto encontrado",
  "Objeto perdido",
  "Objeto apreendido",
  "Cumprimento de ordem de serviço",
  "Cumprimento de mandado",
  "Entrega de documento",
  "Acompanhamento institucional",
  "Visita comunitária",
  "Orientação ao cidadão",
  "Pessoa em surto",
  "Tentativa de suicídio",
  "Auxílio a pessoa vulnerável",
  "Ocorrência administrativa",
  "Ocorrência sem ilicitude",
  "Consulta de CPF",
  "Consulta de veículo",
  "Apoio à Defesa Civil",
  "Patrulha Maria da Penha",
  "Patrulha Escolar",
  "Patrulha Ambiental",
  "Operação conjunta",
  "Blitz educativa",
  "Blitz de trânsito",
  "Apreensão de veículo",
  "Apreensão de objeto",
  "Recuperação de objeto",
  "Auxílio ao turista",
  "Ponto base",
  "Monitoramento de evento",
  "Atendimento preventivo",
  "Outro",
];

export const TIPOS_ENVOLVIDO = [
  "SOLICITANTE",
  "VÍTIMA",
  "AUTOR",
  "SUSPEITO",
  "TESTEMUNHA",
  "CONDUTOR",
  "PROPRIETÁRIO",
  "RESPONSÁVEL",
  "MENOR",
  "ACOMPANHANTE",
];

export const SITUACOES_VEICULO = [
  "ABORDADO",
  "ACIDENTE",
  "APREENDIDO",
  "RECUPERADO",
  "ABANDONADO",
  "FURTO/ROUBO",
  "SUSPEITO",
  "SEM RESTRIÇÃO",
  "COM RESTRIÇÃO",
  "REMOVIDO",
  "LIBERADO",
];

export const OBJETOS_PREDEFINIDOS = {
  "Arma de fogo": {
    tipos: [
      "Revólver",
      "Pistola",
      "Espingarda",
      "Carabina",
      "Fuzil",
      "Submetralhadora",
      "Garrucha",
      "Arma artesanal",
      "Simulacro",
      "Airsoft",
      "Pressão",
    ],
    campos: [
      "tipo",
      "marca",
      "modelo",
      "calibre",
      "numeração",
      "munições",
      "cor",
      "situação",
      "observação",
    ],
  },

  "Arma branca": {
    tipos: [
      "Faca",
      "Facão",
      "Canivete",
      "Punhal",
      "Machado",
      "Tesoura",
      "Estilete",
      "Foice",
      "Espada",
      "Machete",
      "Chave de fenda",
      "Outro",
    ],
    campos: [
      "tipo",
      "tamanho",
      "marca",
      "cor",
      "situação",
      "observação",
    ],
  },

  Munição: {
    tipos: [
      ".22",
      ".32",
      ".38",
      ".380",
      "9mm",
      ".40",
      ".45",
      "5.56",
      "7.62",
      "12",
      "Outro",
    ],
    campos: [
      "calibre",
      "quantidade",
      "marca",
      "situação",
      "observação",
    ],
  },

  Celular: {
    marcas: {
      Apple: [
        "iPhone 8",
        "iPhone X",
        "iPhone 11",
        "iPhone 12",
        "iPhone 13",
        "iPhone 14",
        "iPhone 15",
        "iPhone 16",
        "iPhone 17",
      ],
      Samsung: [
        "Galaxy A10",
        "Galaxy A20",
        "Galaxy A30",
        "Galaxy A50",
        "Galaxy A71",
        "Galaxy S20",
        "Galaxy S21",
        "Galaxy S22",
        "Galaxy S23",
        "Galaxy S24",
      ],
      Motorola: [
        "Moto G8",
        "Moto G9",
        "Moto G10",
        "Moto G20",
        "Moto G30",
        "Moto G60",
      ],
      Xiaomi: [
        "Redmi Note 8",
        "Redmi Note 9",
        "Redmi Note 10",
        "Redmi Note 11",
        "Redmi Note 12",
        "Redmi Note 13",
      ],
      LG: [],
      Nokia: [],
      Huawei: [],
      Realme: [],
      Outro: [],
    },
    campos: [
      "marca",
      "modelo",
      "imei",
      "cor",
      "chip",
      "situação",
      "observação",
    ],
  },

  Documento: {
    tipos: [
      "RG",
      "CPF",
      "CNH",
      "Título de Eleitor",
      "Carteira de Trabalho",
      "Carteira Funcional",
      "Passaporte",
      "CRLV",
      "Certidão de Nascimento",
      "Certidão de Casamento",
      "Outro",
    ],
    campos: [
      "tipo",
      "número",
      "nome",
      "órgão_emissor",
      "situação",
      "observação",
    ],
  },

  Dinheiro: {
    tipos: [
      "Espécie",
      "Moeda",
      "Cheque",
      "Cartão Bancário",
      "Pix",
    ],
    campos: [
      "valor",
      "quantidade",
      "moeda",
      "situação",
      "observação",
    ],
  },

  Droga: {
    tipos: [
      "Maconha",
      "Cocaína",
      "Crack",
      "Haxixe",
      "Lança-perfume",
      "Ecstasy",
      "LSD",
      "Comprimidos",
      "Substância semelhante",
      "Outro",
    ],
    campos: [
      "tipo",
      "quantidade",
      "peso",
      "unidade_peso",
      "embalagem",
      "situação",
      "observação",
    ],
  },

  Veículo: {
    tipos: [
      "Automóvel",
      "Motocicleta",
      "Caminhonete",
      "Caminhão",
      "Ônibus",
      "Van",
      "Bicicleta",
      "Outro",
    ],
    campos: [
      "placa",
      "marca",
      "modelo",
      "cor",
      "ano",
      "chassi",
      "situação",
      "observação",
    ],
  },

  Dinamite: {
    tipos: [
      "Explosivo",
      "Artefato caseiro",
      "Fogos de artifício",
      "Outro",
    ],
    campos: [
      "tipo",
      "quantidade",
      "situação",
      "observação",
    ],
  },

  Ferramenta: {
    tipos: [
      "Marreta",
      "Alicate",
      "Chave de fenda",
      "Pé de cabra",
      "Serra",
      "Furadeira",
      "Outro",
    ],
    campos: [
      "tipo",
      "marca",
      "quantidade",
      "situação",
      "observação",
    ],
  },

  Eletrônico: {
    tipos: [
      "Notebook",
      "Computador",
      "Tablet",
      "Televisão",
      "Caixa de som",
      "Drone",
      "Videogame",
      "Outro",
    ],
    campos: [
      "tipo",
      "marca",
      "modelo",
      "serial",
      "cor",
      "situação",
      "observação",
    ],
  },

  Joia: {
    tipos: [
      "Anel",
      "Corrente",
      "Pulseira",
      "Brinco",
      "Relógio",
      "Pingente",
      "Outro",
    ],
    campos: [
      "tipo",
      "material",
      "quantidade",
      "situação",
      "observação",
    ],
  },

  Outro: {
    tipos: ["Outro"],
    campos: [
      "descrição",
      "quantidade",
      "situação",
      "observação",
    ],
  },
};

export const SITUACOES_OBJETO = [
  "APREENDIDO",
  "RECUPERADO",
  "ENCONTRADO",
  "ENTREGUE",
  "DEVOLVIDO",
  "RECOLHIDO",
  "DANIFICADO",
  "DESTRUÍDO",
  "ABANDONADO",
  "FURTADO",
  "ROUBADO",
  "PERDIDO",
  "RESTITUÍDO",
  "EM ANÁLISE",
  "ENCAMINHADO",
  "SEM IDENTIFICAÇÃO",
];