"use client";
import Link from "next/link"; import { useEffect,useState } from "react"; import { ArrowLeft,Loader2,Save } from "lucide-react"; import { useRouter } from "next/navigation";
import ProtecaoModulo from "@/components/ProtecaoModulo"; import { registrarAuditoria } from "@/lib/auditoria"; import { lerUsuarioCarreira,podeGerenciarCarreira,TIPOS_PROMOCAO } from "@/lib/planoCarreira"; import { supabase } from "@/lib/supabase";
type Guarda={id:number;nome:string;matricula:string|null;cargo:string|null}; type Cargo={id:number;nome:string;classe:string|null;nivel:string|null};
export default function Novo(){const r=useRouter(); const [u]=useState(()=>lerUsuarioCarreira()); const [guardas,setGuardas]=useState<Guarda[]>([]); const [cargos,setCargos]=useState<Cargo[]>([]); const [guardaId,setGuardaId]=useState(""); const [cargoId,setCargoId]=useState(""); const [tipo,setTipo]=useState("PROGRESSAO"); const [obs,setObs]=useState(""); const [saving,setSaving]=useState(false); const [erro,setErro]=useState("");
 useEffect(()=>{async function c(){if(!u?.municipio_id)return; const [g,ca]=await Promise.all([supabase.from("guardas").select("id,nome,matricula,cargo").eq("municipio_id",u.municipio_id).order("nome"),supabase.from("carreira_cargos").select("id,nome,classe,nivel").eq("municipio_id",u.municipio_id).eq("ativo",true).order("ordem")]); setGuardas((g.data as Guarda[])||[]);setCargos((ca.data as Cargo[])||[])}void c()},[]);
 async function salvar(){if(!u||!podeGerenciarCarreira(u.perfil)||!guardaId||!cargoId){setErro("Preencha guarda e cargo pretendido.");return} const g=guardas.find(x=>String(x.id)===guardaId)!; const c=cargos.find(x=>String(x.id)===cargoId)!; setSaving(true); const {data,error}=await supabase.from("carreira_processos").insert({municipio_id:u.municipio_id,guarda_id:g.id,guarda_nome:g.nome,matricula:g.matricula,cargo_atual:g.cargo,cargo_pretendido_id:c.id,cargo_pretendido:`${c.nome}${c.classe?` - ${c.classe}`:""}${c.nivel?` - ${c.nivel}`:""}`,tipo_promocao:tipo,status:"EM_ANALISE",observacoes:obs.trim()||null,criado_por_id:String(u.id),criado_por_nome:u.nome}).select("id").single(); if(error){setErro(error.message);setSaving(false);return} await registrarAuditoria({modulo:"RH",acao:"CRIAR",tabela:"carreira_processos",registro_id:data.id,descricao:`Processo de carreira criado para ${g.nome}.`}); r.push(`/sistema/plano-carreira/${data.id}`)}
 return <ProtecaoModulo modulo="guardas"><main className="min-h-screen bg-[#020b1c] p-5 text-white"><div className="mx-auto max-w-3xl space-y-5"><header className="rounded-3xl border border-cyan-400/15 bg-[#061326] p-6"><Link href="/sistema/plano-carreira" className="inline-flex items-center gap-2 text-sm font-black text-cyan-300"><ArrowLeft className="h-4 w-4"/>Voltar</Link><h1 className="mt-4 text-2xl font-black">Novo processo de promoção</h1></header>{erro&&<div className="rounded-xl border border-rose-400/25 bg-rose-400/10 p-4 text-rose-200">{erro}</div>}<section className="space-y-4 rounded-2xl border border-slate-800 bg-[#061326] p-5"><Campo t="Guarda"><select value={guardaId} onChange={e=>setGuardaId(e.target.value)} className="h-12 w-full rounded-xl border border-slate-700 bg-slate-950/60 px-4"><option value="">Selecione...</option>{guardas.map(g=><option key={g.id} value={g.id}>{g.nome} — {g.matricula||"sem matrícula"}</option>)}</select></Campo><Campo t="Cargo pretendido"><select value={cargoId} onChange={e=>setCargoId(e.target.value)} className="h-12 w-full rounded-xl border border-slate-700 bg-slate-950/60 px-4"><option value="">Selecione...</option>{cargos.map(c=><option key={c.id} value={c.id}>{c.nome} {c.classe||""} {c.nivel||""}</option>)}</select></Campo><Campo t="Modalidade"><select value={tipo} onChange={e=>setTipo(e.target.value)} className="h-12 w-full rounded-xl border border-slate-700 bg-slate-950/60 px-4">{TIPOS_PROMOCAO.map(x=><option key={x}>{x}</option>)}</select></Campo><Campo t="Observações"><textarea value={obs} onChange={e=>setObs(e.target.value)} rows={5} className="w-full rounded-xl border border-slate-700 bg-slate-950/60 p-4"/></Campo></section><div className="flex justify-end"><button disabled={saving} onClick={()=>void salvar()} className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-5 py-3 font-black text-slate-950 disabled:opacity-50">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Criar processo</button></div></div></main></ProtecaoModulo>}
function Campo({t,children}:{t:string;children:React.ReactNode}){return <label className="block space-y-2"><span className="text-xs font-black uppercase text-slate-400">{t}</span>{children}</label>}
